### ISSUE TITLE
Task return "server returned an error: (404) Not Found."

### ISSUE THREAD

**Issue by YanVale** [shayki5/azure-devops-create-pr-task#102]
Hi,

I used your PR as a task in our Pipeline and I have encountered error below.

![image](https://user-images.githubusercontent.com/55928105/120043692-cabf9780-bfe2-11eb-8942-a7b9f9ac6b44.png)

can you help me . 

i think some problem of azure devops api .

The remote server returned an error: (404) Not Found.

info : I use custom name in my azure devops like ' https://capsulecorp.visualtudio.com"

**Comment by shayki5** [comment]
Hן @YanVale,
Can you run the pipeline with `system.debug` = `true` and share here the logs?

**Comment by YanVale** [comment]
Hi shayki5  

thanks for reply ... 

logs in system.debug mode :


2021-05-31T13:01:14.3786357Z ##[debug]Evaluating condition for step: 'Create Pull Request'
2021-05-31T13:01:14.3833904Z ##[debug]Evaluating: succeeded()
2021-05-31T13:01:14.3840367Z ##[debug]Evaluating succeeded:
2021-05-31T13:01:14.3888561Z ##[debug]=> True
2021-05-31T13:01:14.3898591Z ##[debug]Result: True
2021-05-31T13:01:14.3949102Z ##[section]Starting: Create Pull Request
2021-05-31T13:01:14.4824797Z ==============================================================================
2021-05-31T13:01:14.4825336Z Task         : Create Pull Request
2021-05-31T13:01:14.4826000Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2021-05-31T13:01:14.4826369Z Version      : 1.2.225
2021-05-31T13:01:14.4826737Z Author       : Shayki Abramczyk
2021-05-31T13:01:14.4827392Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2021-05-31T13:01:14.4827977Z ==============================================================================
2021-05-31T13:01:17.1789773Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2021-05-31T13:01:17.4025419Z ##[debug]Entering RunTask.
2021-05-31T13:01:17.4494494Z ##[debug]INPUT_SOURCEBRANCH: 'refs/heads/sprint5'
2021-05-31T13:01:17.4559928Z ##[debug]INPUT_TARGETBRANCH: 'develop'
2021-05-31T13:01:17.4608931Z ##[debug]INPUT_TITLE: 'merge da sprint refs/heads/sprint5 para branch develop Backend.20210527-10'
2021-05-31T13:01:17.4629166Z ##[debug]INPUT_DESCRIPTION: 'merge do brache sprint para develop - Backend'
2021-05-31T13:01:17.4653806Z ##[debug]INPUT_REVIEWERS (empty)
2021-05-31T13:01:17.4709755Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2021-05-31T13:01:17.4774147Z ##[debug]INPUT_ISDRAFT: 'false'
2021-05-31T13:01:17.4776094Z ##[debug] Converted to bool: False
2021-05-31T13:01:17.4799816Z ##[debug]INPUT_AUTOCOMPLETE: 'false'
2021-05-31T13:01:17.4816893Z ##[debug] Converted to bool: False
2021-05-31T13:01:17.4841439Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2021-05-31T13:01:17.5383400Z ##[debug]INPUT_DELETESOURCH: 'false'
2021-05-31T13:01:17.5399629Z ##[debug] Converted to bool: False
2021-05-31T13:01:17.5422748Z ##[debug]INPUT_COMMITMESSAGE (empty)
2021-05-31T13:01:17.5459574Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2021-05-31T13:01:17.5480188Z ##[debug] Converted to bool: False
2021-05-31T13:01:17.5496938Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2021-05-31T13:01:17.5513437Z ##[debug] Converted to bool: True
2021-05-31T13:01:17.5535553Z ##[debug]INPUT_PROJECTID (empty)
2021-05-31T13:01:17.5559006Z ##[debug]INPUT_GITREPOSITORYID (empty)
2021-05-31T13:01:17.5581217Z ##[debug]INPUT_GITHUBREPOSITORY (empty)
2021-05-31T13:01:17.5605280Z ##[debug]INPUT_PASSPULLREQUESTIDBACKTOADO: 'false'
2021-05-31T13:01:17.5621391Z ##[debug] Converted to bool: False
2021-05-31T13:01:17.5652566Z ##[debug]INPUT_ISFORKED: 'false'
2021-05-31T13:01:17.5666883Z ##[debug] Converted to bool: False
2021-05-31T13:01:17.5688723Z ##[debug]INPUT_BYPASSPOLICY: 'false'
2021-05-31T13:01:17.5704466Z ##[debug] Converted to bool: False
2021-05-31T13:01:17.5726232Z ##[debug]INPUT_BYPASSREASON (empty)
2021-05-31T13:01:17.5854610Z ##[debug]ENDPOINT_URL_SystemVssConnection: 'https://xxxxx.vsrm.visualstudio.com/'
2021-05-31T13:01:17.5876490Z ##[debug]ENDPOINT_AUTH_SystemVssConnection: '********'
2021-05-31T13:01:17.7062222Z ##[debug]ENDPOINT_DATA_SystemVssConnection (empty)
2021-05-31T13:01:17.7456967Z The Source Branch is: refs/heads/sprint5
2021-05-31T13:01:17.7462262Z The Target Branch is: refs/heads/develop
2021-05-31T13:01:17.7470037Z The Title is: merge da sprint refs/heads/sprint5 para branch develop Backend.20210527-10
2021-05-31T13:01:17.7478637Z The Description is: merge do brache sprint para develop - Backend
2021-05-31T13:01:17.7485097Z Is Reviewers are: 
2021-05-31T13:01:17.7524522Z Is Draft Pull Request: False
2021-05-31T13:01:17.7531868Z Auto-Complete: False
2021-05-31T13:01:17.7538459Z Link Work Items: True
2021-05-31T13:01:17.7545003Z Bypass: False
2021-05-31T13:01:17.7551550Z Bypass Reason: 
2021-05-31T13:01:17.7869278Z ##[debug]GET https://xxxxxx.visualstudio.com/BR-Metals-SVP/_apis/git/repositories//diffs/commits?baseVersion=sprint5&targetVersion=develop&api-version=4.0&$top=2 with 0-byte payload
2021-05-31T13:01:17.9644498Z ##[debug]Leaving RunTask.
2021-05-31T13:01:17.9711243Z ##[debug]Caught exception from task script.
2021-05-31T13:01:17.9737339Z ##[debug]Error record:
2021-05-31T13:01:18.0700064Z ##[debug]Invoke-RestMethod : {"$id":"1","innerException":null,"message":"TF401019: The Git repository with name or identifier diffs does not exist or you do not have permissions for the operation you are attempting.","typeName":"Microsoft.TeamFoundation.Git.Server.GitRepositoryNotFoundException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitRepositoryNotFoundException","errorCode":0,"eventId":3000}
2021-05-31T13:01:18.0710470Z ##[debug]At D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.225\createPullRequest.ps1:432 char:17
2021-05-31T13:01:18.0727264Z ##[debug]+ ... $response = Invoke-RestMethod -Uri $url -Method Get -Headers $head -C ...
2021-05-31T13:01:18.0740833Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-05-31T13:01:18.0754017Z ##[debug]    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc    eption
2021-05-31T13:01:18.0773900Z ##[debug]    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
2021-05-31T13:01:18.0810653Z ##[debug]Script stack trace:
2021-05-31T13:01:18.0824456Z ##[debug]at CheckIfThereAreChanges, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.225\createPullRequest.ps1: line 432
2021-05-31T13:01:18.0829776Z ##[debug]at CreateAzureDevOpsPullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.225\createPullRequest.ps1: line 308
2021-05-31T13:01:18.0840893Z ##[debug]at CreatePullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.225\createPullRequest.ps1: line 139
2021-05-31T13:01:18.0851331Z ##[debug]at RunTask, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.225\createPullRequest.ps1: line 98
2021-05-31T13:01:18.0871923Z ##[debug]at <ScriptBlock>, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.225\createPullRequest.ps1: line 777
2021-05-31T13:01:18.0879563Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-05-31T13:01:18.0893570Z ##[debug]at <ScriptBlock>, <No file>: line 22
2021-05-31T13:01:18.0904926Z ##[debug]at <ScriptBlock>, <No file>: line 18
2021-05-31T13:01:18.0916005Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-05-31T13:01:18.0936854Z ##[debug]Exception:
2021-05-31T13:01:18.1077551Z ##[debug]System.Net.WebException: The remote server returned an error: (404) Not Found.
2021-05-31T13:01:18.1091047Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2021-05-31T13:01:18.1101984Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2021-05-31T13:01:18.1388902Z ##[error]The remote server returned an error: (404) Not Found.
2021-05-31T13:01:18.1399648Z ##[debug]Processed: ##vso[task.logissue type=error]The remote server returned an error: (404) Not Found.
2021-05-31T13:01:18.1410027Z ##[debug]Processed: ##vso[task.complete result=Failed]
2021-05-31T13:01:18.2135321Z ##[section]Finishing: Create Pull Request

**Comment by YanVale** [comment]
im set  system.debug in build pipeline , but the results is sucesss ( the previous image is from release pipelines task)

info: is the same build source branch 



##[debug]Evaluating condition for step: 'Create Pull Request'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
Starting: Create Pull Request
==============================================================================
Task         : Create Pull Request
Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
Version      : 1.2.225
Author       : Shayki Abramczyk
Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
==============================================================================
##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
##[debug]Entering RunTask.
##[debug]INPUT_SOURCEBRANCH: 'refs/heads/sprint5'
##[debug]INPUT_TARGETBRANCH: 'develop'
##[debug]INPUT_TITLE: 'merge da sprint refs/heads/sprint5 para branch develop Backend.20210531-1'
##[debug]INPUT_DESCRIPTION: 'merge da sprint refs/heads/sprint5 para branch develop Backend.20210531-1'
##[debug]INPUT_REVIEWERS (empty)
##[debug]INPUT_REPOTYPE: 'Azure DevOps'
##[debug]INPUT_ISDRAFT: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_AUTOCOMPLETE: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
##[debug]INPUT_DELETESOURCH: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_COMMITMESSAGE (empty)
##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_LINKWORKITEMS: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_PROJECTID (empty)
##[debug]INPUT_GITREPOSITORYID (empty)
##[debug]INPUT_GITHUBREPOSITORY: 'BrMetalsSVPBackend'
##[debug]INPUT_PASSPULLREQUESTIDBACKTOADO: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_ISFORKED: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_BYPASSPOLICY: 'false'
##[debug] Converted to bool: False
##[debug]INPUT_BYPASSREASON (empty)
##[debug]ENDPOINT_URL_SystemVssConnection: 'https://xxxxx.visualstudio.com/'

**Comment by YanVale** [comment]
Im see two differents urls apis in logs:

https://xxxx.visualstudio.com/BR-Metals-SVP/_apis/git/repositories//diffs/commits?baseVersion=sprint5&targetVersion=develop&api-version=4.0&$top=2 - (broken in release pipeline)

https://xxxx.visualstudio.com/BR-Metals-SVP/_apis/git/repositories/BrMetalsSVPBackend/diffs/commits?baseVersion=sprint5&targetVersion=develop&api-version=4.0&$top=2 - ( sucess task in build pipeline )

the first link matches //difs and the second matches the correct repo . my suggest is a problem when mount search in the urls apis

**Comment by shayki5** [comment]
@YanVale can you share the task configuration in the release pipeline?

**Comment by YanVale** [comment]
sure ..  @shayki5 

my task in release 


![image](https://user-images.githubusercontent.com/55928105/120207631-0e90e780-c203-11eb-8ccf-8fec4c269c2d.png)

**Comment by shayki5** [comment]
@YanVale I think I found the issue.
In the "Repository to use" press on "Select" and choose the repo name from the list.

**Comment by YanVale** [comment]
@shayki5 

Thanks so much .  It works for me .

really , i have two different repositories  .
