### ISSUE TITLE
Error (404) Not Found for PR when PR-repo not same as source code

### ISSUE THREAD

**Issue by ivan-luxoft** [shayki5/azure-devops-create-pr-task#106]
Hello,

I am get error when set parameters:
```
repositorySelectionMethod: select
projectId: 'CreatePR_FromOneToAnotherRepository'
gitRepositoryId: 'TargetOne'```

where gitRepositoryId different from repository with source code for build
screenshot (left repo for PR same as source code, right - differen)
![chrome_2lVBrRt6I5](https://user-images.githubusercontent.com/75603957/124816242-f3876500-df70-11eb-9752-1fb29b88e685.png)

settings task:
![image](https://user-images.githubusercontent.com/75603957/124816338-0ef27000-df71-11eb-9aa3-f8e948626e58.png)

If I change repo for source code, but not change another settings - task successful runs and PR created

**Comment by shayki5** [comment]
Hi, can you run the pipeline with `system.debug` = `true` and share here the logs?
Did you grant the permissions in the second project & repo?

**Comment by ivan-luxoft** [comment]
debug log for task attached 
[log.txt](https://github.com/shayki5/azure-devops-create-pr-task/files/6799132/log.txt)

permissions was set for repositories on the project level, all repository in the same project
![chrome_8719QfYKxs](https://user-images.githubusercontent.com/75603957/125243306-95eb7380-e2f6-11eb-897c-22bf96df93c4.png)

also I tried to give permissions of all types but it doesn't work
![chrome_BtfxWcz3SM](https://user-images.githubusercontent.com/75603957/125243471-d3e89780-e2f6-11eb-8ea9-e110cab1c27d.png)

**Comment by shayki5** [comment]
Thank you!
I can reproduce the issue.
Look like my code support only forks repos from the same project, I will add a support also from other projects, I hope I will have time soon :)

**Comment by shayki5** [comment]
Wait, is it forked repo or just 2 different repos in 2 projects?

**Comment by ivan-luxoft** [comment]
it is two different repos, I want copy files from first to second, then commit second and create pullrequest (it is bump pr or update shared files)

I looked code and think that token can usage without [call method](https://github.com/shayki5/azure-devops-create-pr-task/blob/dc6479e4456cc095ed573adb0e9c002375c25d42/task/createPullRequest.ps1#L50) `Get-VstsEndpoint` ()

**Comment by shayki5** [comment]
You can't create a PR for 2 different repos, even in the UI. this is how git works.

**Comment by ivan-luxoft** [comment]
I know it =) , I want copy files from the source repository to the target (locally on agent), then commit copying files to the target repo and created PR with commit changes in target repo

**Comment by shayki5** [comment]
Who should do the copy & commit? is it in your pipeline?

**Comment by ivan-luxoft** [comment]
yes, it is task/action/script in the pipeline

**Comment by shayki5** [comment]
can you share your full pipeline?

**Comment by ivan-luxoft** [comment]
I'm not implemented functional for copy and commit =)
In this time I having trouble with creating PR for repository if build run not from him.

**Comment by shayki5** [comment]
I tried in my organization and I succeeded to create the PR for a repo that is different then the "get sources" repo. 
Can you try to give permissions also to the following groups?
![image](https://user-images.githubusercontent.com/26063853/125455825-fd598a40-451c-48ce-b218-cf338e482d90.png)

**Comment by ivan-luxoft** [comment]
I set all permissions for these groups, also I add build service account in this group, but for me it is not working,
I try it for another organization later

**Comment by ivang7** [comment]
I cant successfull run task with source code from one repository and pr in another (
I gave all permission what I can seen

**Comment by shayki5** [comment]
Can you give me permissions to your organization? I will try to check it.

**Comment by ivan-luxoft** [comment]
service account for build has all permissions on organization level:
![chrome_A10VmukSC3](https://user-images.githubusercontent.com/75603957/126161308-a8e6c7c4-55d7-4f79-b932-3adf0c3b3701.png)

account included in the group (with all permissions) on the organization level:
![chrome_A10VmukSC3](https://user-images.githubusercontent.com/75603957/126161428-30842d9d-0bde-40d9-963e-052b6e6a69cc.png)

account and groups has all permissions on the project (repositories):
![chrome_mYXB1vbJ0D](https://user-images.githubusercontent.com/75603957/126161687-a9c78e44-8c2f-44a6-9ddc-342779f26e1c.png)

**Comment by shayki5** [comment]
Thank you!
Please grant permissions also to the user **Project Collection Build Service (ivang0848)**:
![image](https://user-images.githubusercontent.com/26063853/126165906-33c12ed0-1370-4285-a09d-f487f7705c5d.png)

**Comment by ivan-luxoft** [comment]
I added all permission, but previously I not seen this service account (and now I found it by search)

**Comment by AnshumanTripathy** [comment]
Have the same issue, have provided access to the Accounts as mentioned, still have 404. Trying to run the pipeline in a different Project 1. Is it possible to merge from Project 2 to Project 3(forked).

**Comment by shayki5** [comment]
@AnshumanTripathy When it forked repos it's impossible, I will add it soon!
If it is not forked repos, just repo in another project are you success?

**Comment by shayki5** [comment]
@ivan-luxoft any news? are you able to create a PR?

**Comment by shayki5** [comment]
@BGajda13 Are the repos in 2 different projects?

**Comment by BGajda13** [comment]
@shayki5 Repos are in the same project.

**Comment by shayki5** [comment]
So It should be OK, can you share a screenshot of the permissions you gave?

**Comment by BGajda13** [comment]
![image](https://user-images.githubusercontent.com/32744989/162010263-49892767-88f2-4ce5-84ad-9df89ff452d1.png)
![image](https://user-images.githubusercontent.com/32744989/162010477-a1ef6b62-af98-43e6-9bb3-dd43ed8b27f4.png)

**Comment by shayki5** [comment]
@BGajda13 Try to give the permissions also to these users:
![image](https://user-images.githubusercontent.com/26063853/162134476-63f4709e-2cfd-45ed-bc60-43f6a101115e.png)

**Comment by daviegy** [comment]
Hi @shayki5, just following up on this thread as I faced similar issue. I have followed all the necessary steps to grant permission as recommended. But, I still get 404

![image](https://user-images.githubusercontent.com/24591554/202427974-07dadd09-aca3-464b-a030-79dba989eea2.png)

**Comment by shayki5** [comment]
Hi @daviegy, are the branches in the same repo?

**Comment by daviegy** [comment]
> 

yes, please.

**Comment by shayki5** [comment]
Can you run it with `system.debug` = `true` and share here the logs?

**Comment by daviegy** [comment]
> Can you run it with `system.debug` = `true` and share here the logs?

2022-11-17T11:47:13.2374824Z ##[debug]Evaluating condition for step: 'CPR from Master to other environment'
2022-11-17T11:47:13.2376697Z ##[debug]Evaluating: succeeded()
2022-11-17T11:47:13.2377104Z ##[debug]Evaluating succeeded:
2022-11-17T11:47:13.2378158Z ##[debug]=> True
2022-11-17T11:47:13.2378636Z ##[debug]Result: True
2022-11-17T11:47:13.2379072Z ##[section]Starting: CPR from Master to other environment
2022-11-17T11:47:13.2517736Z ==============================================================================
2022-11-17T11:47:13.2518004Z Task         : Create Pull Request
2022-11-17T11:47:13.2518335Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2022-11-17T11:47:13.2518818Z Version      : 1.2.335
2022-11-17T11:47:13.2518989Z Author       : Shayki Abramczyk
2022-11-17T11:47:13.2519264Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2022-11-17T11:47:13.2519621Z ==============================================================================
2022-11-17T11:47:14.7520610Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2022-11-17T11:47:14.9645825Z ##[debug]Entering RunTask.
2022-11-17T11:47:15.0057023Z ##[debug]INPUT_SOURCEBRANCH: 'Master'
2022-11-17T11:47:15.0086664Z ##[debug]INPUT_TARGETBRANCH: 'QA'
2022-11-17T11:47:15.0116716Z ##[debug]INPUT_TITLE: 'Update branch with latest build from master'
2022-11-17T11:47:15.0145594Z ##[debug]INPUT_DESCRIPTION (empty)
2022-11-17T11:47:15.0228049Z ##[debug]INPUT_REVIEWERS (empty)
2022-11-17T11:47:15.0813215Z ##[debug]INPUT_TAGS (empty)
2022-11-17T11:47:15.0841191Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2022-11-17T11:47:15.0868892Z ##[debug]INPUT_ISDRAFT: 'false'
2022-11-17T11:47:15.0945476Z ##[debug] Converted to bool: False
2022-11-17T11:47:15.1046435Z ##[debug]INPUT_AUTOCOMPLETE: 'true'
2022-11-17T11:47:15.1096419Z ##[debug] Converted to bool: True
2022-11-17T11:47:15.1157579Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2022-11-17T11:47:15.1196501Z ##[debug]INPUT_DELETESOURCH (empty)
2022-11-17T11:47:15.1223220Z ##[debug] Converted to bool: False
2022-11-17T11:47:15.1252937Z ##[debug]INPUT_DELETESOURCE: 'false'
2022-11-17T11:47:15.1272923Z ##[debug] Converted to bool: False
2022-11-17T11:47:15.1297328Z ##[debug]INPUT_COMMITMESSAGE (empty)
2022-11-17T11:47:15.1331923Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2022-11-17T11:47:15.1353790Z ##[debug] Converted to bool: False
2022-11-17T11:47:15.1381229Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2022-11-17T11:47:15.1432311Z ##[debug] Converted to bool: True
2022-11-17T11:47:15.1491799Z ##[debug]INPUT_PROJECTID: '0e0451b2-95ef-43f2-923c-3dca57e67f19'
2022-11-17T11:47:15.1524086Z ##[debug]INPUT_GITREPOSITORYID: '7370628f-7d63-4bdc-925f-8926dddd9aca'
2022-11-17T11:47:15.1553223Z ##[debug]INPUT_GITHUBREPOSITORY: 'GateForce.xxx.Solution'
2022-11-17T11:47:15.1607612Z ##[debug]INPUT_PASSPULLREQUESTIDBACKTOADO: 'false'
2022-11-17T11:47:15.1628776Z ##[debug] Converted to bool: False
2022-11-17T11:47:15.1686471Z ##[debug]INPUT_ISFORKED: 'false'
2022-11-17T11:47:15.1721069Z ##[debug] Converted to bool: False
2022-11-17T11:47:15.1787158Z ##[debug]INPUT_BYPASSPOLICY: 'false'
2022-11-17T11:47:15.1817042Z ##[debug] Converted to bool: False
2022-11-17T11:47:15.2882374Z ##[debug]INPUT_BYPASSREASON (empty)
2022-11-17T11:47:15.2883653Z ##[debug]INPUT_ALWAYSCREATEPR: 'false'
2022-11-17T11:47:15.2884619Z ##[debug] Converted to bool: False
2022-11-17T11:47:15.2885585Z ##[debug]INPUT_GITHUBAUTOMERGE: 'false'
2022-11-17T11:47:15.2886607Z ##[debug] Converted to bool: False
2022-11-17T11:47:15.2889209Z ##[debug]INPUT_GITHUBMERGECOMMITTITLE (empty)
2022-11-17T11:47:15.2951378Z ##[debug]INPUT_GITHUBMERGECOMMITMESSAGE (empty)
2022-11-17T11:47:15.2978079Z ##[debug]INPUT_GITHUBMERGESTRATEGY: 'merge'
2022-11-17T11:47:15.3005133Z ##[debug]INPUT_GITHUBDELETESOURCEBRANCH: 'false'
2022-11-17T11:47:15.3022758Z ##[debug] Converted to bool: False
2022-11-17T11:47:15.3262981Z ##[debug]ENDPOINT_URL_SystemVssConnection: 'https://dev.azure.com/crowdforce/'
2022-11-17T11:47:15.3336046Z ##[debug]ENDPOINT_AUTH_SystemVssConnection: '********'
2022-11-17T11:47:15.3366417Z ##[debug]ENDPOINT_DATA_SystemVssConnection (empty)
2022-11-17T11:47:15.4501477Z The repository is: 7370628f-7d63-4bdc-925f-8926dddd9aca
2022-11-17T11:47:15.4513608Z The Source Branch is: refs/heads/Master
2022-11-17T11:47:15.4520483Z The Target Branch is: refs/heads/QA
2022-11-17T11:47:15.4545593Z The Title is: Update branch with latest build from master
2022-11-17T11:47:15.4557808Z The Description is: 
2022-11-17T11:47:15.4606763Z Is Reviewers are: 
2022-11-17T11:47:15.4637048Z The tags are: 
2022-11-17T11:47:15.4773389Z Is Draft Pull Request: False
2022-11-17T11:47:15.4823481Z Auto-Complete: True
2022-11-17T11:47:15.4851480Z Link Work Items: True
2022-11-17T11:47:15.4881626Z Bypass: False
2022-11-17T11:47:15.4895167Z Bypass Reason: 
2022-11-17T11:47:15.4905351Z DeleteSourceBranch ist set to: False
2022-11-17T11:47:15.6412886Z ##[debug]GET https://dev.azure.com/crowdforce/0e0451b2-95ef-43f2-923c-3dca57e67f19/_apis/git/repositories/7370628f-7d63-4bdc-925f-8926dddd9aca/diffs/commits?baseVersion=QA&targetVersion=Master&api-version=4.0&diffCommonCommit=true&$top=2 with 0-byte payload
2022-11-17T11:47:15.8991084Z ##[debug]Leaving RunTask.
2022-11-17T11:47:15.9199611Z ##[debug]Caught exception from task script.
2022-11-17T11:47:15.9239718Z ##[debug]Error record:
2022-11-17T11:47:16.0359863Z ##[debug]Invoke-RestMethod : {"$id":"1","innerException":null,"message":"TF401175:The version descriptor  could not be resolved to a version in the repository GateForce.xxx.Solution","typeName":"Microsoft.TeamFoundation.Git.Server.GitUnresolvableToCommitException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitUnresolvableToCommitException","errorCode":0,"eventId":3000}
2022-11-17T11:47:16.0399598Z ##[debug]At D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.335\createPullRequest.ps1:620 char:17
2022-11-17T11:47:16.0417421Z ##[debug]+ ... $response = Invoke-RestMethod -Uri $url -Method Get -Headers $head -C ...
2022-11-17T11:47:16.0457199Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2022-11-17T11:47:16.0478038Z ##[debug]    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc    eption
2022-11-17T11:47:16.0519791Z ##[debug]    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
2022-11-17T11:47:16.0621099Z ##[debug]Script stack trace:
2022-11-17T11:47:16.0679594Z ##[debug]at CheckIfThereAreChanges, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.335\createPullRequest.ps1: line 620
2022-11-17T11:47:16.0698243Z ##[debug]at CreateAzureDevOpsPullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.335\createPullRequest.ps1: line 481
2022-11-17T11:47:16.0714842Z ##[debug]at CreatePullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.335\createPullRequest.ps1: line 176
2022-11-17T11:47:16.0760614Z ##[debug]at RunTask, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.335\createPullRequest.ps1: line 122
2022-11-17T11:47:16.0778051Z ##[debug]at <ScriptBlock>, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.335\createPullRequest.ps1: line 994
2022-11-17T11:47:16.0793703Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-11-17T11:47:16.0810042Z ##[debug]at <ScriptBlock>, <No file>: line 22
2022-11-17T11:47:16.0843254Z ##[debug]at <ScriptBlock>, <No file>: line 18
2022-11-17T11:47:16.0864922Z ##[debug]at <ScriptBlock>, <No file>: line 1
2022-11-17T11:47:16.0888942Z ##[debug]Exception:
2022-11-17T11:47:16.0944975Z ##[debug]System.Net.WebException: The remote server returned an error: (404) Not Found.
2022-11-17T11:47:16.0965572Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2022-11-17T11:47:16.0986833Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2022-11-17T11:47:16.1444399Z ##[error]The remote server returned an error: (404) Not Found.
2022-11-17T11:47:16.1456875Z ##[debug]Processed: ##vso[task.logissue type=error]The remote server returned an error: (404) Not Found.
2022-11-17T11:47:16.1463831Z ##[debug]Processed: ##vso[task.complete result=Failed]
2022-11-17T11:47:16.2086034Z ##[section]Finishing: CPR from Master to other environment

**Comment by shayki5** [comment]
Are you using azure devops or github? can you share your yaml?

**Comment by daviegy** [comment]
> Are you using azure devops or github? can you share your yaml?

I use Azure devops

![image](https://user-images.githubusercontent.com/24591554/202446489-bd7e2ebc-0691-4878-b926-6f64b99e3524.png)


pool:
  name: Azure Pipelines
steps:
- task: ShaykiAbramczyk.CreatePullRequest.CreatePullRequest.CreatePullRequest@1
  displayName: 'CPR from Master to other environment'
  inputs:
    repositorySelector: select
    projectId: '0e0451b2-95ef-43f2-923c-3dca57e67f19'
    gitRepositoryId: '7370628f-7d63-4bdc-925f-8926dddd9aca'
    sourceBranch: Master
    targetBranch: QA
    title: 'Update branch with latest build from master'
    autoComplete: true

**Comment by shayki5** [comment]
I just see this line in the logs:
`##[debug]INPUT_GITHUBREPOSITORY: 'GateForce.xxx.Solution'`
what is GateForce.xxx.Solution? 
Can you try to add a new task and configure the details?

**Comment by daviegy** [comment]
@shayki5 , thanks I was able to get it working. I figured out, I had wrong settings in my pipeline.

**Comment by suddrey** [comment]
Hi @daviegy - could you please advise what you changed to get it working? I am having the same error despite having all of the correct permissions set.

Thank you.

**Comment by daviegy** [comment]
> Hi @daviegy - could you please advise what you changed to get it working? I am having the same error despite having all of the correct permissions set.
> 
> Thank you.

Hi suddrey,  in my case after setting all necessary permission, checking for casing on my branch name helped fix my issue. 


For example, if your branch name is  _**Master**_ and you type **_master_**  in the pipeline setup it won't work. The naming has to match in terms of casing
