### ISSUE TITLE
Method invocation failed because [System.String] does not contain a method named 'ForEach'.

### ISSUE THREAD

**Issue by VetriZotec** [shayki5/azure-devops-create-pr-task#115]
2021-10-29T19:40:19.5573150Z ##[debug]Evaluating condition for step: 'Create Pull Request to master branch'
2021-10-29T19:40:19.5575155Z ##[debug]Evaluating: succeeded()
2021-10-29T19:40:19.5575773Z ##[debug]Evaluating succeeded:
2021-10-29T19:40:19.5577078Z ##[debug]=> True
2021-10-29T19:40:19.5577982Z ##[debug]Result: True
2021-10-29T19:40:19.5578794Z ##[section]Starting: Create Pull Request to master branch
2021-10-29T19:40:19.5720941Z ==============================================================================
2021-10-29T19:40:19.5721311Z Task         : Create Pull Request
2021-10-29T19:40:19.5721764Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2021-10-29T19:40:19.5722181Z Version      : 1.2.257
2021-10-29T19:40:19.5722485Z Author       : Shayki Abramczyk
2021-10-29T19:40:19.5722883Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2021-10-29T19:40:19.5723461Z ==============================================================================
2021-10-29T19:40:20.5479589Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2021-10-29T19:40:20.7494917Z ##[debug]Entering RunTask.
2021-10-29T19:40:20.7829870Z ##[debug]INPUT_SOURCEBRANCH: 'refs/heads/zp-release/21.21.00'
2021-10-29T19:40:20.7870509Z ##[debug]INPUT_TARGETBRANCH: 'master'
2021-10-29T19:40:20.8004468Z ##[debug]INPUT_TITLE: 'Merge 21.21.00.08  prod tag into master branch'
2021-10-29T19:40:20.8006491Z ##[debug]INPUT_DESCRIPTION: 'Merge 21.21.00.08  prod tag into master branch'
2021-10-29T19:40:20.8007950Z ##[debug]INPUT_REVIEWERS (empty)
2021-10-29T19:40:20.8031536Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2021-10-29T19:40:20.8117091Z ##[debug]INPUT_ISDRAFT: 'false'
2021-10-29T19:40:20.8118481Z ##[debug] Converted to bool: False
2021-10-29T19:40:20.8139280Z ##[debug]INPUT_AUTOCOMPLETE: 'false'
2021-10-29T19:40:20.8160156Z ##[debug] Converted to bool: False
2021-10-29T19:40:20.8190723Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2021-10-29T19:40:20.8221675Z ##[debug]INPUT_DELETESOURCH: 'false'
2021-10-29T19:40:20.8242821Z ##[debug] Converted to bool: False
2021-10-29T19:40:20.8273553Z ##[debug]INPUT_COMMITMESSAGE: 'Merge 21.21.00.08  prod tag into master branch'
2021-10-29T19:40:20.8308396Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'true'
2021-10-29T19:40:20.8331075Z ##[debug] Converted to bool: True
2021-10-29T19:40:20.8366060Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2021-10-29T19:40:20.8386662Z ##[debug] Converted to bool: True
2021-10-29T19:40:20.8417313Z ##[debug]INPUT_PROJECTID: '21713897-7a17-42f8-888c-cb9be76820fa'
2021-10-29T19:40:20.8450218Z ##[debug]INPUT_GITREPOSITORYID: '43410451-cd42-43f8-a134-9f000c5f5ac0'
2021-10-29T19:40:20.8486063Z ##[debug]INPUT_GITHUBREPOSITORY: 'Service.EncounterUpdate'
2021-10-29T19:40:20.8518068Z ##[debug]INPUT_PASSPULLREQUESTIDBACKTOADO: 'false'
2021-10-29T19:40:20.8551875Z ##[debug] Converted to bool: False
2021-10-29T19:40:20.8584941Z ##[debug]INPUT_ISFORKED: 'false'
2021-10-29T19:40:20.8615479Z ##[debug] Converted to bool: False
2021-10-29T19:40:20.8651079Z ##[debug]INPUT_BYPASSPOLICY: 'false'
2021-10-29T19:40:20.8677921Z ##[debug] Converted to bool: False
2021-10-29T19:40:20.8709055Z ##[debug]INPUT_BYPASSREASON (empty)
2021-10-29T19:40:20.8853299Z ##[debug]ENDPOINT_URL_SystemVssConnection: 'https://zotecp.vsrm.visualstudio.com/'
2021-10-29T19:40:20.8882806Z ##[debug]ENDPOINT_AUTH_SystemVssConnection: '********'
2021-10-29T19:40:20.9143215Z ##[debug]ENDPOINT_DATA_SystemVssConnection (empty)
2021-10-29T19:40:20.9454201Z The repository is: 43410451-cd42-43f8-a134-9f000c5f5ac0
2021-10-29T19:40:20.9460148Z The Source Branch is: refs/heads/zp-release/21.21.00
2021-10-29T19:40:20.9467002Z The Target Branch is: refs/heads/master
2021-10-29T19:40:20.9474119Z The Title is: Merge 21.21.00.08  prod tag into master branch
2021-10-29T19:40:20.9481035Z The Description is: Merge 21.21.00.08  prod tag into master branch
2021-10-29T19:40:20.9536706Z Is Reviewers are: 
2021-10-29T19:40:20.9544262Z Is Draft Pull Request: False
2021-10-29T19:40:20.9551189Z Auto-Complete: False
2021-10-29T19:40:20.9558255Z Link Work Items: True
2021-10-29T19:40:20.9565335Z Bypass: False
2021-10-29T19:40:20.9780350Z Bypass Reason: 
2021-10-29T19:40:21.1145391Z ##[debug]GET https://zotec.visualstudio.com/-42f8-888c-cb9be76820fa/_apis/git/repositories/43f8-a134-9f000c5f5ac0/diffs/commits?baseVersion=zp-release/21.21.00&targetVersion=master&api-version=4.0&$top=2 with 0-byte payload
2021-10-29T19:40:21.3281683Z ##[debug]received 262-byte response of content type application/json; charset=utf-8; api-version=4.0
2021-10-29T19:40:21.3573713Z 5 new commits! perform a Pull Request...
2021-10-29T19:40:21.3609127Z ##[debug]POST https://zotecvisualstudio.com/8c-cb9be76820fa/_apis/git/repositories/00c5f5ac0/commitsBatch?api-version=4.0 with -1-byte payload
2021-10-29T19:40:21.4458246Z ##[debug]received 4176-byte response of content type application/json; charset=utf-8; api-version=4.0
2021-10-29T19:40:21.4749764Z ##[debug]@{count=5; value=System.Object[]}
2021-10-29T19:40:21.4871423Z ##[debug]@{id=19067; url=https://zotec.visualstudio.com/_apis/wit/workItems/19067}
2021-10-29T19:40:21.4916280Z ##[debug]@{id=19067; url=https://zotec.visualstudio.com/_apis/wit/workItems/19067}
2021-10-29T19:40:21.4958852Z ##[debug]@{id=19067; url=https://zotec.visualstudio.com/_apis/wit/workItems/19067}
2021-10-29T19:40:21.4965091Z ##[debug]@{id=19067; url=https://zotec.visualstudio.com/_apis/wit/workItems/19067}
2021-10-29T19:40:21.5021117Z ##[debug]@{id=19067; url=https://zotec.visualstudio.com/_apis/wit/workItems/19067}
2021-10-29T19:40:21.5143581Z ##[debug]19067
2021-10-29T19:40:21.5171058Z ##[debug]@{id=19067; url=https://zotec.visualstudio.com/_apis/wit/workItems/19067}
2021-10-29T19:40:21.5241018Z ##[debug]19067
2021-10-29T19:40:21.5244225Z ##[debug]19067
2021-10-29T19:40:21.5245136Z ##[debug]@{id=19067; url=https://zotec.visualstudio.com/_apis/wit/workItems/19067}
2021-10-29T19:40:21.5252706Z ##[debug]19067
2021-10-29T19:40:21.5276435Z ##[debug]19067
2021-10-29T19:40:21.5294765Z ##[debug]19067
2021-10-29T19:40:21.5319240Z ##[debug]@{id=19067; url=https://zotec.visualstudio.com/_apis/wit/workItems/19067}
2021-10-29T19:40:21.5341776Z ##[debug]19067
2021-10-29T19:40:21.5366130Z ##[debug]19067
2021-10-29T19:40:21.5387664Z ##[debug]19067
2021-10-29T19:40:21.5410072Z ##[debug]19067
2021-10-29T19:40:21.5591236Z ##[debug]Leaving RunTask.
2021-10-29T19:40:21.5648736Z ##[debug]Caught exception from task script.
2021-10-29T19:40:21.5692316Z ##[debug]Error record:
2021-10-29T19:40:21.6744019Z ##[debug]GetLinkedWorkItems : Method invocation failed because [System.String] does not contain a method named 'ForEach'.
2021-10-29T19:40:21.6763809Z ##[debug]At C:\VSTS\A1\build_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.257\createPullRequest.ps1:336 char:22
2021-10-29T19:40:21.6778339Z ##[debug]+         $workItems = GetLinkedWorkItems -teamProject $teamProject -repositoryNam ...
2021-10-29T19:40:21.6794409Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-10-29T19:40:21.6809693Z ##[debug]    + CategoryInfo          : InvalidOperation: (:) [GetLinkedWorkItems], Runt    imeException
2021-10-29T19:40:21.6830415Z ##[debug]    + FullyQualifiedErrorId : MethodNotFound,GetLinkedWorkItems
2021-10-29T19:40:21.6845607Z ##[debug] 
2021-10-29T19:40:21.6869617Z ##[debug]Script stack trace:
2021-10-29T19:40:21.6950546Z ##[debug]at GetLinkedWorkItems, C:\VSTS\A1\build_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.257\createPullRequest.ps1: line 647
2021-10-29T19:40:21.6966484Z ##[debug]at CreateAzureDevOpsPullRequest, C:\VSTS\A1\build_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.257\createPullRequest.ps1: line 336
2021-10-29T19:40:21.6978136Z ##[debug]at CreatePullRequest, C:\VSTS\A1\build_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.257\createPullRequest.ps1: line 140
2021-10-29T19:40:21.7003174Z ##[debug]at RunTask, C:\VSTS\A1\build_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.257\createPullRequest.ps1: line 99
2021-10-29T19:40:21.7016205Z ##[debug]at <ScriptBlock>, C:\VSTS\A1\build_work\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.257\createPullRequest.ps1: line 788
2021-10-29T19:40:21.7044223Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-10-29T19:40:21.7059858Z ##[debug]at <ScriptBlock>, <No file>: line 22
2021-10-29T19:40:21.7072384Z ##[debug]at <ScriptBlock>, <No file>: line 18
2021-10-29T19:40:21.7085298Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-10-29T19:40:21.7107216Z ##[debug]Exception:
2021-10-29T19:40:21.7161809Z ##[debug]System.Management.Automation.RuntimeException: Method invocation failed because [System.String] does not contain a method named 'ForEach'.
2021-10-29T19:40:21.7173951Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2021-10-29T19:40:21.7187421Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2021-10-29T19:40:21.7201256Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2021-10-29T19:40:21.7213764Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2021-10-29T19:40:21.7225237Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2021-10-29T19:40:21.7237518Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2021-10-29T19:40:21.7249397Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2021-10-29T19:40:21.7261587Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2021-10-29T19:40:21.7273780Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2021-10-29T19:40:21.7562354Z ##[error]Method invocation failed because [System.String] does not contain a method named 'ForEach'.
2021-10-29T19:40:21.7571768Z ##[debug]Processed: ##vso[task.logissue type=error]Method invocation failed because [System.String] does not contain a method named 'ForEach'.
2021-10-29T19:40:21.7574009Z ##[debug]Processed: ##vso[task.complete result=Failed]
2021-10-29T19:40:21.7938579Z ##[section]Finishing: Create Pull Request to master branch

**Comment by shayki5** [comment]
Hi,
Is it happenes always or just now?

**Comment by VetriZotec** [comment]
This is the first time i have setup it up. out of 8 pipelines only one pipeline task was successful. rest of them gave the same error.

**Comment by shayki5** [comment]
@VetriZotec can you give me read permissions to your project?

**Comment by VetriZotec** [comment]
not sure about that...
i will check with our security team. but if you can give some steps, with which  i can get more info for you, that will also be good...

**Comment by shayki5** [comment]
@VetriZotec sure. 
try to run the following rest api (`POST`):
` https://zotecvisualstudio.com/8c-cb9be76820fa/_apis/git/repositories/00c5f5ac0/commitsBatch?api-version=4.0` 
with the body:

```
    $body = @{
        '$top'           = 101
        includeWorkItems = "true"
        itemVersion      = @{
            versionOptions = 0
            versionType    = 0
            version        = "master"
        }
        compareVersion   = @{
            versionOptions = 0
            versionType    = 0
            version        = "refs/heads/zp-release/21.21.00"
        }
    }
```

paste here the response please.

**Comment by VetriZotec** [comment]
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://spsprodeus24.vssps.visualstudio.com/_signin?realm=zotec.visualstudio.com&amp;reply_to=https%3A%2F%2Fzotec.visualstudio.com%2F21713897-7a17-42f8-888c-cb9be76820fa%2F_apis%2Fgit%2Frepositories%2F43410451-cd42-43f8-a134-9f000c5f5ac0%2FcommitsBatch%3Fapi-version%3D4.0&amp;redirect=1&amp;hid=c9f4c823-47c5-44a2-9d6a-3cfd00458752&amp;context=eyJodCI6MiwiaGlkIjoiMjFiZDUwNjUtMGI4Mi00Mzk4LTlhMjctMGExMjIwNjAzMzAxIiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2">here</a>.</h2>
</body></html>

**Comment by VetriZotec** [comment]
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://spsprodeus24.vssps.visualstudio.com/_signin?realm=zotecpartnersllc.visualstudio.com&amp;reply_to=https%3A%2F%2Fzotecpartnersllc.visualstudio.com%2F21713897-7a17-42f8-888c-cb9be76820fa%2F_apis%2Fgit%2Frepositories%2F43410451-cd42-43f8-a134-9f000c5f5ac0%2FcommitsBatch%3Fapi-version%3D4.0&amp;redirect=1&amp;hid=c9f4c823-47c5-44a2-9d6a-3cfd00458752&amp;context=eyJodCI6MiwiaGlkIjoiMjFiZDUwNjUtMGI4Mi00Mzk4LTlhMjctMGExMjIwNjAzMzAxIiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2">here</a>.</h2>
</body></html>

**Comment by VetriZotec** [comment]
i am not sure if you are able to see the output properly... in the above comment

**Comment by shayki5** [comment]
as I wrote it should be `POST` api, and not `GET`...

**Comment by VetriZotec** [comment]
hmm i did use the POST command. i used 'curl -X POST with -d @file.txt ( which has the body" with -k

**Comment by shayki5** [comment]
hmm ok, the error is confusing...
can you try do it with Powershell?

**Comment by VetriZotec** [comment]
PS C:\Vetri\azdo\Applications> Invoke-WebRequest -Uri https://zotec.visualstudio.com/27-42f8-888c-
cb9be76820fa/_apis/git/repositories/4341134-9f000c5f5ac0/commitsBatch?api-version=4.0 -Method POST -Body
 @$file


StatusCode        : 203
StatusDescription : Non-Authoritative Information
Content           :

                    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
                    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">




                    <html lang="en-US">
                    <head><title>

                                Azure DevOps Servi...
RawContent        : HTTP/1.1 203 Non-Authoritative Information
                    Pragma: no-cache
                    Content-Length: 15873
                    Cache-Control: no-cache, no-store, must-revalidate
                    Content-Type: text/html; charset=utf-8
                    Expires: -1
                    P3P: CP="C...
Forms             : {}
Headers           : {[Pragma, no-cache], [Content-Length, 15873], [Cache-Control, no-cache, no-store,
                    must-revalidate], [Content-Type, text/html; charset=utf-8]...}
Images            : {}
InputFields       : {@{innerHTML=; innerText=; outerHTML=<input name="__RequestVerificationToken" type="hidden" value="
                    SeFc9jbmn7M6PnFzM-91SzcuBSvdVuMEIVWLQVR9PhIIf-etdvJF7iki4geuR7HY085-55TB0_kMelK0Hr50eZCQtW81">;
                    outerText=; tagName=INPUT; name=__RequestVerificationToken; type=hidden; value=SeFc9jbmn7M6PnFzM-91
                    SzcuBSvdVuMEIVWLQVR9PhIIf-etdvJF7iki4geuR7HY085-55TB0_kMelK0Hr50eZCQtW81}, @{innerHTML=;
                    innerText=; outerHTML=<input name="__RequestVerificationToken2" type="hidden"
                    value="__RequestVerificationToken2e0d9fdef-2a56-47ed-a9a4-b677332ee8df">; outerText=;
                    tagName=INPUT; name=__RequestVerificationToken2; type=hidden;
                    value=__RequestVerificationToken2e0d9fdef-2a56-47ed-a9a4-b677332ee8df}}
Links             : {@{innerHTML=Anonymous; innerText=Anonymous; outerHTML=<a title="Anonymous"
                    class=":SignedOutProfileElement: createProfileLink" href="/go/profile">Anonymous</a>;
                    outerText=Anonymous; tagName=A; title=Anonymous; class=:SignedOutProfileElement:
                    createProfileLink; href=/go/profile}, @{innerHTML=Sign out; innerText=Sign out; outerHTML=<a
                    class="scarabLink" href="/_signout">Sign out</a>; outerText=Sign out; tagName=A; class=scarabLink;
                    href=/_signout}}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 15873



PS C:\Vetri\azdo\Applications>

**Comment by shayki5** [comment]
Now it's authentication issue, try to run it with the flag `-UseDefaultCredentials`.

**Comment by VetriZotec** [comment]
Hmm I looked at all the documentation of Azure Plugin for a pipeline build task and I am not able to find where I will mention this flag and how.
Following is my sample build task for checkmax scan :
  - task: checkmarx.cxsast.cx-scan-task.Application security ***@***.***
    displayName: 'Security static source code analysis for $(BLDNUM)'
    inputs:
      CheckmarxService: Checkmarx
      customPreset: 'Zotec Default'
      projectName: $(PROJECT)
      fullTeamName: 'CxServer\SP\Company\Users'
      folderExclusion: 'cvs, .svn, .hg , .git, .bzr, bin , obj,  backup, .idea, node_modules, packages $(FLDREXCLUDE)'
      fileExtension: |
       !*.DS_Store, !*.ipr,     !*.iws,
       !*.bak,    !*.tmp,     !*.aac,      !*.aif,      !*.iff,     !*.m3u,   !*.mid,   !*.mp3,
       !*.mpa,    !*.ra,        !*.wav,      !*.wma,      !*.3g2,     !*.3gp,   !*.asf,   !*.asx,
       !*.avi,    !*.flv,       !*.mov,     !*.mp4,      !*.mpg,     !*.rm,    !*.swf,   !*.vob,
       !*.wmv,    !*.bmp,       !*.gif,       !*.jpg,      !*.png,     !*.psd,   !*.tif,   !*.swf,
       !*.jar,    !*.zip,       !*.rar,      !*.exe,      !*.dll,     !*.pdb,   !*.7z,    !*.gz,
       !*.tar.gz, !*.tar,       !*.gz,       !*.ahtm,     !*.ahtml,   !*.fhtml, !*.hdm,
       !*.hdml,   !*.hsql,      !*.ht,      !*.hta,      !*.htc,     !*.htd,   !*.war,   !*.ear,
       !*.htmls,  !*.ihtml,     !*.mht,      !*.mhtm,     !*.mhtml,   !*.ssi,   !*.stm,
       $(FILEEXCLUSION)
      comment: 'Security Scan for $(PROJECT) $(BLDNUM)'
      syncMode: false
      vulnerabilityThreshold: true
      enableDependencyScan: true
      dependencyServerURL: 'Checkmarx-SCA'
      dependencyTenant: builds
      dependencyFolderExclusion: 'cvs, .svn, .hg , .git, .bzr, bin , obj,  backup, .idea, node_modules, packages'
      sastCaChainFilePath: 'c:\zotec-sca-chain.crt'
      scaCaChainFilePath: 'c:\zotec-sca-chain.crt'




Vetrichelvi  Jayaprakasan
Senior DevOps Engineer I

P

***@***.***

Visit us at:
http://www.zotecpartners.com

[https://www.zotecpartners.com/zpllc_logo_ironport.gif]

Zotec Partners, LLC disclaimer<http://www.zotecpartners.com/electronic_disclaimer.html> information

**Comment by shayki5** [comment]
@VetriZotec i'm sorry but i'm not related to Checkmarx....

**Comment by VetriZotec** [comment]
Sooo sorry,
I was working on checkmarx issue too and got mixed up.

I will now use this option on my create pull request task and see if its works for me or not
Thanks
Vetri


Vetrichelvi  Jayaprakasan
Senior DevOps Engineer I

P

***@***.***

Visit us at:
http://www.zotecpartners.com

[https://www.zotecpartners.com/zpllc_logo_ironport.gif]

Zotec Partners, LLC disclaimer<http://www.zotecpartners.com/electronic_disclaimer.html> information

**Comment by VetriZotec** [comment]
i am using your extension in classic mode of pipelines and i don't see a flag for -UseDefaultCredentials . please let me know how to implement it.

**Comment by shayki5** [comment]
I meant to add it to your PS script you tried to run.

**Comment by VetriZotec** [comment]
PS C:\Vetri\azdo\Applications>Invoke-WebRequest -Uri https://zotec.visualstudio.com/27-42f8-888c-
cb9be76820fa/_apis/git/repositories/4341134-9f000c5f5ac0/commitsBatch?api-version=4.0 -Method POST -Body
 @$file -UseDefaultCredentials


StatusCode        : 203
StatusDescription : Non-Authoritative Information
Content           :

                    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
                    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">




                    <html lang="en-US">
                    <head><title>

                                Azure DevOps Servi...
RawContent        : HTTP/1.1 203 Non-Authoritative Information
                    Pragma: no-cache
                    Content-Length: 15904
                    Cache-Control: no-cache, no-store, must-revalidate
                    Content-Type: text/html; charset=utf-8
                    Expires: -1
                    P3P: CP="C...
Forms             : {}
Headers           : {[Pragma, no-cache], [Content-Length, 15904], [Cache-Control, no-cache, no-store,
                    must-revalidate], [Content-Type, text/html; charset=utf-8]...}
Images            : {}
InputFields       : {@{innerHTML=; innerText=; outerHTML=<input name="__RequestVerificationToken" type="hidden" value="
                    X3dxcUJaY-uGnErbqhA5KXuzyLu44oESYkOm9mH2IUW7ddMIlvovsZBgIL5vrmtS9R7BvxVxwRKpAFQuc-A9h9R3e_I1">;
                    outerText=; tagName=INPUT; name=__RequestVerificationToken; type=hidden; value=X3dxcUJaY-uGnErbqhA5
                    KXuzyLu44oESYkOm9mH2IUW7ddMIlvovsZBgIL5vrmtS9R7BvxVxwRKpAFQuc-A9h9R3e_I1}, @{innerHTML=;
                    innerText=; outerHTML=<input name="__RequestVerificationToken2" type="hidden"
                    value="__RequestVerificationToken2fe7351cc-4ef6-49d0-be59-2e1663c86162">; outerText=;
                    tagName=INPUT; name=__RequestVerificationToken2; type=hidden;
                    value=__RequestVerificationToken2fe7351cc-4ef6-49d0-be59-2e1663c86162}}
Links             : {@{innerHTML=Anonymous; innerText=Anonymous; outerHTML=<a title="Anonymous"
                    class=":SignedOutProfileElement: createProfileLink" href="/go/profile">Anonymous</a>;
                    outerText=Anonymous; tagName=A; title=Anonymous; class=:SignedOutProfileElement:
                    createProfileLink; href=/go/profile}, @{innerHTML=Sign out; innerText=Sign out; outerHTML=<a
                    class="scarabLink" href="/_signout">Sign out</a>; outerText=Sign out; tagName=A; class=scarabLink;
                    href=/_signout}}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 15904

**Comment by shayki5** [comment]
Hi, do you still have issues?

**Comment by VetriZotec** [comment]
yes, but it works sometimes and sometimes not... not sure what causes it
i am using this to merge prod released codes... into master branch. so it can be different branches, if it major release, minor release or a hotfix... does that help ?

**Comment by shayki5** [comment]
It's hard to me to debug the issue 😕 because you can't run the api, looks like permissions issue.
If you don't link work items is it still occurs?

**Comment by shayki5** [comment]
@VetriZotec any news? are you able to create a PR?

**Comment by VetriZotec** [comment]
I have implemented your extension for my post release tasks… and now I have errors only some time….

So I am ok with it.
Thanks for checking back.
Vetri

**Comment by shayki5** [comment]
@VetriZotec 👌
