### ISSUE TITLE
Getting error The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel

### ISSUE THREAD

**Issue by Swapnika483** [shayki5/azure-devops-create-pr-task#167]

**Comment by shayki5** [comment]
Hi, can you share the full log?

**Comment by TenaciousG** [comment]
I'm getting the same error since yesterday (version 1.2.357).
2023-06-08T07:22:17.1002661Z ##[section]Starting: Create Translations Pull Request
2023-06-08T07:22:17.1107874Z ==============================================================================
2023-06-08T07:22:17.1107996Z Task         : Create Pull Request
2023-06-08T07:22:17.1108054Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2023-06-08T07:22:17.1108215Z Version      : 1.2.357
2023-06-08T07:22:17.1108279Z Author       : Shayki Abramczyk
2023-06-08T07:22:17.1108807Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2023-06-08T07:22:17.1108927Z ==============================================================================
2023-06-08T07:22:18.0476380Z The repository is: MyRepo
2023-06-08T07:22:18.0486049Z The Source Branch is: refs/heads/ops/cxxxxx
2023-06-08T07:22:18.0493462Z The Target Branch is: refs/heads/yyyyy
2023-06-08T07:22:18.0502640Z The Title is: New Translations
2023-06-08T07:22:18.0511114Z The Description is: New translations from Crowdin
2023-06-08T07:22:18.0519528Z Is Reviewers are: xxxxxxxx
2023-06-08T07:22:18.0527616Z The tags are: 
2023-06-08T07:22:18.0568729Z Is Draft Pull Request: False
2023-06-08T07:22:18.0577342Z Auto-Complete: True
2023-06-08T07:22:18.0585636Z Link Work Items: True
2023-06-08T07:22:18.0593716Z Bypass: False
2023-06-08T07:22:18.0602059Z Bypass Reason: 
2023-06-08T07:22:18.0610087Z DeleteSourceBranch ist set to: True
2023-06-08T07:22:18.4014154Z AlwaysCreatePr flag is false. A PR will only be created if there are actual file changes, but not if there is only a difference in commits.
2023-06-08T07:22:18.4076599Z 1 new commits! File changes were found! Perform a Pull Request...
2023-06-08T07:22:19.2079811Z ##[error]The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
2023-06-08T07:22:19.2395631Z ##[section]Finishing: Create Translations Pull Request

**Comment by shayki5** [comment]
Are you behind a proxy?

**Comment by TenaciousG** [comment]
Nope, just running plain ms hosted azure devops/pipelines on my repo hosted in the same azure devops project

**Comment by shayki5** [comment]
It's Azure DevOps in the cloud or Azure DevOps Server on prem?

**Comment by shayki5** [comment]
Can you run it with diagnostic enabled and share the logs? I tests the new version and it working for me, I want to see where is the exact issue.

**Comment by shayki5** [comment]
If I will revert iI won't be able to debug it... anyway, can you try remove the reviewers?

**Comment by TenaciousG** [comment]
before removing the reviewers:
```
##[debug]Invoke-RestMethod : The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
##[debug]At D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.357\createPullRequest.ps1:754 char:27
##[debug]+ ... dentities = Invoke-RestMethod -Uri $url -Method Get -ContentType appl ...
##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc    eption
##[debug]    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
##[debug] 
##[debug]Script stack trace:
##[debug]at GetReviewerId, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.357\createPullRequest.ps1: line 754
##[debug]at CreateAzureDevOpsPullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.357\createPullRequest.ps1: line 505
##[debug]at CreatePullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.357\createPullRequest.ps1: line 180
##[debug]at RunTask, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.357\createPullRequest.ps1: line 126
##[debug]at <ScriptBlock>, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.357\createPullRequest.ps1: line 966
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
##[debug]   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
##[debug]   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
##[debug]   --- End of inner exception stack trace ---
##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
##[error]The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
##[debug]Processed: ##vso[task.logissue type=error]The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
##[debug]Processed: ##vso[task.complete result=Failed]
Finishing: Create Translations Pull Request

```

**Comment by TenaciousG** [comment]
and works when removing reviewers

**Comment by shayki5** [comment]
I've updated the extension, can you try now? (version 1.2.359)

**Comment by TenaciousG** [comment]
Seems to be working again now. Thank you for the efficient support!
