### ISSUE TITLE
After update to version 1.2.55  - [error]Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported.

### ISSUE THREAD

**Issue by JonasMock** [shayki5/azure-devops-create-pr-task#20]
2019-12-31T02:50:33.0379760Z ##[debug]Evaluating condition for step: 'DEV build succeeded - automatic pull request'
2019-12-31T02:50:33.0380521Z ##[debug]Evaluating: succeeded()
2019-12-31T02:50:33.0380611Z ##[debug]Evaluating succeeded:
2019-12-31T02:50:33.0380925Z ##[debug]=> True
2019-12-31T02:50:33.0381125Z ##[debug]Result: True
2019-12-31T02:50:33.0381338Z ##[section]Starting: DEV build succeeded - automatic pull request
2019-12-31T02:50:33.0488819Z ==============================================================================
2019-12-31T02:50:33.0488895Z Task         : Create Pull Request
2019-12-31T02:50:33.0488926Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2019-12-31T02:50:33.0488955Z Version      : 1.2.55
2019-12-31T02:50:33.0488995Z Author       : Shayki Abramczyk
2019-12-31T02:50:33.0489024Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2019-12-31T02:50:33.0489071Z ==============================================================================
2019-12-31T02:50:33.9123486Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2019-12-31T02:50:34.1093857Z ##[debug]Entering RunTask.
2019-12-31T02:50:34.1496555Z ##[debug]INPUT_SOURCEBRANCH: 'Development'
2019-12-31T02:50:34.1529875Z ##[debug]INPUT_TARGETBRANCH: 'master'
2019-12-31T02:50:34.1628035Z ##[debug]INPUT_TITLE: 'DEV build succeeded - automatic pull request'
2019-12-31T02:50:34.1629738Z ##[debug]INPUT_DESCRIPTION (empty)
2019-12-31T02:50:34.1655240Z ##[debug]INPUT_REVIEWERS (empty)
2019-12-31T02:50:34.1687137Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2019-12-31T02:50:34.1754139Z ##[debug]INPUT_ISDRAFT: 'false'
2019-12-31T02:50:34.1754755Z ##[debug] Converted to bool: False
2019-12-31T02:50:34.1782183Z ##[debug]INPUT_AUTOCOMPLETE: 'false'
2019-12-31T02:50:34.1801662Z ##[debug] Converted to bool: False
2019-12-31T02:50:34.1831468Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2019-12-31T02:50:34.1860061Z ##[debug]INPUT_DELETESOURCH: 'false'
2019-12-31T02:50:34.1880364Z ##[debug] Converted to bool: False
2019-12-31T02:50:34.1908354Z ##[debug]INPUT_COMMITMESSAGE (empty)
2019-12-31T02:50:34.1938770Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2019-12-31T02:50:34.1961327Z ##[debug] Converted to bool: False
2019-12-31T02:50:34.1993298Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2019-12-31T02:50:34.2014556Z ##[debug] Converted to bool: True
2019-12-31T02:50:34.2341812Z The Source Branch is: refs/heads/Development
2019-12-31T02:50:34.2349449Z The Target Branch is: refs/heads/master
2019-12-31T02:50:34.2357004Z The Title is: DEV build succeeded - automatic pull request
2019-12-31T02:50:34.2364748Z The Description is: 
2019-12-31T02:50:34.2405439Z Is Draft Pull Request: False
2019-12-31T02:50:34.4535010Z ##[debug]{
2019-12-31T02:50:34.4550013Z ##[debug]    "compareVersion":  {
2019-12-31T02:50:34.4565593Z ##[debug]                           "versionOptions":  0,
2019-12-31T02:50:34.4582921Z ##[debug]                           "versionType":  0,
2019-12-31T02:50:34.4598072Z ##[debug]                           "version":  "Development"
2019-12-31T02:50:34.4614061Z ##[debug]                       },
2019-12-31T02:50:34.4630486Z ##[debug]    "itemVersion":  {
2019-12-31T02:50:34.4647086Z ##[debug]                        "versionOptions":  0,
2019-12-31T02:50:34.4662855Z ##[debug]                        "versionType":  0,
2019-12-31T02:50:34.4677964Z ##[debug]                        "version":  "master"
2019-12-31T02:50:34.4692253Z ##[debug]                    },
2019-12-31T02:50:34.4707035Z ##[debug]    "$top":  101,
2019-12-31T02:50:34.5206864Z ##[debug]    "includeWorkItems":  "true"
2019-12-31T02:50:34.5336007Z ##[debug]}
2019-12-31T02:50:34.5441473Z ##[debug]POST https://dev.azure.com/jonasmock/MQTT_WiFi_Relais/_apis/git/repositories/MQTT_WiFi_Relais/commitsBatch?api-version=4.1 with -1-byte payload
2019-12-31T02:50:34.6193027Z ##[debug]received 1440-byte response of content type application/json; charset=utf-8; api-version=4.1
2019-12-31T02:50:34.6243821Z ##[debug]@{count=2; value=System.Object[]}
2019-12-31T02:50:34.7688715Z ##[debug]Leaving RunTask.
2019-12-31T02:50:34.8362491Z ##[debug]Caught exception from task script.
2019-12-31T02:50:34.8399468Z ##[debug]Error record:
2019-12-31T02:50:34.9180898Z ##[debug]GetLinkedWorkItems : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported.
2019-12-31T02:50:34.9194893Z ##[debug]At D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.55\createPullRequest.ps1:241 char:22
2019-12-31T02:50:34.9209329Z ##[debug]+ ... workItems = GetLinkedWorkItems -sourceBranch $sourceBranch.Remove(0,  ...
2019-12-31T02:50:34.9224108Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-12-31T02:50:34.9237685Z ##[debug]    + CategoryInfo          : InvalidArgument: (:) [GetLinkedWorkItems], ParameterBindingException
2019-12-31T02:50:34.9250428Z ##[debug]    + FullyQualifiedErrorId : CannotConvertArgument,GetLinkedWorkItems
2019-12-31T02:50:34.9264296Z ##[debug] 
2019-12-31T02:50:34.9340870Z ##[debug]Script stack trace:
2019-12-31T02:50:34.9341771Z ##[debug]at GetLinkedWorkItems, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.55\createPullRequest.ps1: line 343
2019-12-31T02:50:34.9342088Z ##[debug]at CreateAzureDevOpsPullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.55\createPullRequest.ps1: line 241
2019-12-31T02:50:34.9356463Z ##[debug]at CreatePullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.55\createPullRequest.ps1: line 80
2019-12-31T02:50:34.9370687Z ##[debug]at RunTask, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.55\createPullRequest.ps1: line 38
2019-12-31T02:50:34.9386813Z ##[debug]at <ScriptBlock>, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.55\createPullRequest.ps1: line 429
2019-12-31T02:50:34.9402321Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-12-31T02:50:34.9416747Z ##[debug]at <ScriptBlock>, <No file>: line 22
2019-12-31T02:50:34.9431911Z ##[debug]at <ScriptBlock>, <No file>: line 18
2019-12-31T02:50:34.9446155Z ##[debug]at <ScriptBlock>, <No file>: line 1
2019-12-31T02:50:34.9468135Z ##[debug]Exception:
2019-12-31T02:50:35.0081955Z ##[debug]System.Management.Automation.ParameterBindingException: Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported. ---> System.NotSupportedException: Specified method is not supported.
2019-12-31T02:50:35.0110222Z ##[debug]   at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)
2019-12-31T02:50:35.0113790Z ##[debug]   --- End of inner exception stack trace ---
2019-12-31T02:50:35.0114020Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
2019-12-31T02:50:35.0115076Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
2019-12-31T02:50:35.0115487Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-12-31T02:50:35.0115758Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-12-31T02:50:35.0116007Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
2019-12-31T02:50:35.0116246Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
2019-12-31T02:50:35.0116480Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
2019-12-31T02:50:35.0117797Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
2019-12-31T02:50:35.0118085Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
2019-12-31T02:50:35.0171047Z ##[error]Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported.
2019-12-31T02:50:35.0180295Z ##[debug]Processed: ##vso[task.logissue type=error]Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Message'. Specified method is not supported.
2019-12-31T02:50:35.0192304Z ##[debug]Processed: ##vso[task.complete result=Failed]
2019-12-31T02:50:35.0683920Z ##[section]Finishing: DEV build succeeded - automatic pull request

**Comment by JonasMock** [comment]
Without the option "Link Work Items" it works.

**Comment by shayki5** [comment]
Hi @JonasMock,
Thank you for reporting that!
It's related to issue #18.
I just fixed it, please check :)

**Comment by JonasMock** [comment]
Thank’s for your fast help, it works now.
