### ISSUE TITLE
Broken after 1.2.77

### ISSUE THREAD

**Issue by interpeix** [shayki5/azure-devops-create-pr-task#30]
Hi, after the upgrade of 1.2.77 version our pipeline is raising 400 error.

Here is the debug log:

`2020-02-10T14:28:21.3903799Z ##[section]Starting: Create Pull Request
2020-02-10T14:28:21.4003458Z ==============================================================================
2020-02-10T14:28:21.4003515Z Task         : Create Pull Request
2020-02-10T14:28:21.4003563Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-02-10T14:28:21.4003596Z Version      : 1.2.77
2020-02-10T14:28:21.4003627Z Author       : Shayki Abramczyk
2020-02-10T14:28:21.4003673Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-02-10T14:28:21.4003714Z ==============================================================================
2020-02-10T14:28:22.2738031Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-02-10T14:28:22.4411770Z ##[debug]Entering RunTask.
2020-02-10T14:28:22.4866181Z ##[debug]INPUT_SOURCEBRANCH: 'master'
2020-02-10T14:28:22.4897174Z ##[debug]INPUT_TARGETBRANCH: 'develop/*'
2020-02-10T14:28:22.4992904Z ##[debug]INPUT_TITLE: 'Bajada de codigo desde Master'
2020-02-10T14:28:22.4993472Z ##[debug]INPUT_DESCRIPTION: 'Pull request automatico'
2020-02-10T14:28:22.4993765Z ##[debug]INPUT_REVIEWERS (empty)
2020-02-10T14:28:22.5040010Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2020-02-10T14:28:22.5106781Z ##[debug]INPUT_ISDRAFT: 'false'
2020-02-10T14:28:22.5111333Z ##[debug] Converted to bool: False
2020-02-10T14:28:22.5139376Z ##[debug]INPUT_AUTOCOMPLETE: 'true'
2020-02-10T14:28:22.5161176Z ##[debug] Converted to bool: True
2020-02-10T14:28:22.5190526Z ##[debug]INPUT_MERGESTRATEGY: 'noFastForward'
2020-02-10T14:28:22.5222265Z ##[debug]INPUT_DELETESOURCH: 'false'
2020-02-10T14:28:22.5236720Z ##[debug] Converted to bool: False
2020-02-10T14:28:22.5263266Z ##[debug]INPUT_COMMITMESSAGE (empty)
2020-02-10T14:28:22.5292010Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2020-02-10T14:28:22.5311116Z ##[debug] Converted to bool: False
2020-02-10T14:28:22.5338105Z ##[debug]INPUT_LINKWORKITEMS: 'true'
2020-02-10T14:28:22.5356960Z ##[debug] Converted to bool: True
2020-02-10T14:28:22.5386046Z ##[debug]INPUT_PROJECTID (empty)
2020-02-10T14:28:22.5412416Z ##[debug]INPUT_GITREPOSITORYID (empty)
2020-02-10T14:28:22.8874962Z The Source Branch is: refs/heads/master
2020-02-10T14:28:22.8884557Z The Target Branch is: refs/heads/develop/BOR
2020-02-10T14:28:22.8893774Z The Title is: Bajada de codigo desde Master
2020-02-10T14:28:22.8900511Z The Description is: Pull request automatico
2020-02-10T14:28:22.8950994Z Is Draft Pull Request: False
2020-02-10T14:28:23.0359173Z ##[debug]{
2020-02-10T14:28:23.0373510Z ##[debug]    "compareVersion":  {
2020-02-10T14:28:23.0386297Z ##[debug]                           "versionOptions":  0,
2020-02-10T14:28:23.0400158Z ##[debug]                           "versionType":  0,
2020-02-10T14:28:23.0413348Z ##[debug]                           "version":  "master"
2020-02-10T14:28:23.0426706Z ##[debug]                       },
2020-02-10T14:28:23.0440140Z ##[debug]    "itemVersion":  {
2020-02-10T14:28:23.0453589Z ##[debug]                        "versionOptions":  0,
2020-02-10T14:28:23.0466619Z ##[debug]                        "versionType":  0,
2020-02-10T14:28:23.0479850Z ##[debug]                        "version":  "develop/BOR"
2020-02-10T14:28:23.1519469Z ##[debug]                    },
2020-02-10T14:28:23.1660599Z ##[debug]    "$top":  101,
2020-02-10T14:28:23.1670247Z ##[debug]    "includeWorkItems":  "true"
2020-02-10T14:28:23.1671132Z ##[debug]}
2020-02-10T14:28:23.1765178Z ##[debug]POST https://dev.azure.com/innovationstrategies//_apis/git/repositories//commitsBatch?api-version=4.1 with -1-byte payload
2020-02-10T14:28:23.5844729Z ##[debug]Leaving RunTask.
2020-02-10T14:28:23.6105218Z ##[debug]Caught exception from task script.
2020-02-10T14:28:23.6138970Z ##[debug]Error record:
2020-02-10T14:28:23.6778819Z ##[debug]Invoke-RestMethod : {"$id":"1","innerException":null,"message":"A valid repository name is required.\r\nParameter name: Name","typeName":"Microsoft.TeamFoundation.SourceControl.WebServer.InvalidArgumentValueException, Microsoft.TeamFoundation.SourceControl.WebServer","typeKey":"InvalidArgumentValueException","errorCode":0,"eventId":0}
2020-02-10T14:28:23.6786660Z ##[debug]At D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.77\createPullRequest.ps1:365 char:17
2020-02-10T14:28:23.6798701Z ##[debug]+ ... $response = Invoke-RestMethod -Method Post -Uri $url -Headers $header ...
2020-02-10T14:28:23.6810436Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-02-10T14:28:23.6821971Z ##[debug]    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc    eption
2020-02-10T14:28:23.6833636Z ##[debug]    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
2020-02-10T14:28:23.6906135Z ##[debug]Script stack trace:
2020-02-10T14:28:23.6906994Z ##[debug]at GetLinkedWorkItems, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.77\createPullRequest.ps1: line 365
2020-02-10T14:28:23.6907388Z ##[debug]at CreateAzureDevOpsPullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.77\createPullRequest.ps1: line 257
2020-02-10T14:28:23.6907771Z ##[debug]at CreatePullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.77\createPullRequest.ps1: line 94
2020-02-10T14:28:23.6918662Z ##[debug]at <ScriptBlock>, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.77\createPullRequest.ps1: line 61
2020-02-10T14:28:23.6930965Z ##[debug]at RunTask, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.77\createPullRequest.ps1: line 57
2020-02-10T14:28:23.6942566Z ##[debug]at <ScriptBlock>, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.77\createPullRequest.ps1: line 463
2020-02-10T14:28:23.6953858Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-02-10T14:28:23.6964968Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-02-10T14:28:23.6976164Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-02-10T14:28:23.6987380Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-02-10T14:28:23.7007143Z ##[debug]Exception:
2020-02-10T14:28:23.7544743Z ##[debug]System.Net.WebException: The remote server returned an error: (400) Bad Request.
2020-02-10T14:28:23.7581351Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2020-02-10T14:28:23.7582315Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2020-02-10T14:28:23.7631733Z ##[error]The remote server returned an error: (400) Bad Request.
2020-02-10T14:28:23.7640307Z ##[debug]Processed: ##vso[task.logissue type=error]The remote server returned an error: (400) Bad Request.
2020-02-10T14:28:23.7654307Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-02-10T14:28:23.7901341Z ##[section]Finishing: Create Pull Request
2020-02-10T14:28:23.7915631Z ##[debug]Evaluating condition for step: 'Checkout Iberostar.diCRS@master to s'
2020-02-10T14:28:23.7916503Z ##[debug]Evaluating: AlwaysNode()
2020-02-10T14:28:23.7916601Z ##[debug]Evaluating AlwaysNode:
2020-02-10T14:28:23.7917609Z ##[debug]=> True
2020-02-10T14:28:23.7917845Z ##[debug]Result: True`

It seems that some mandatory param(maybe repositoryName) is missing.

**Comment by shayki5** [comment]
Hi @interpeix,
Thank you for reporting that!
I indeed forgot to update the code when the target branch is with a wildcard (/*)...
I fixed it, please check now of it works :)

**Comment by interpeix** [comment]
Cool @shayki5, it's fixed!! :) 
Thanks for you quick response and support.

**Comment by shayki5** [comment]
You're welcome! 
I glad it works :)
