### ISSUE TITLE
Cannot process argument because the value of argument "path" is null. Change the value of argument "path" to a non-null value.

### ISSUE THREAD

**Issue by blakito** [shayki5/azure-devops-create-pr-task#46]
Hi mate. Congrats for the great work.

Im having an issue with my pipeline. The full debug log is below.

Couldn't find any path variables and messing with source/target repositories didnt worked also.

Thanks in advance

2020-06-06T21:27:17.1744134Z ==============================================================================
2020-06-06T21:27:17.1744569Z Task         : Create Pull Request
2020-06-06T21:27:17.1745025Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-06-06T21:27:17.1745482Z Version      : 1.2.133
2020-06-06T21:27:17.1745712Z Author       : Shayki Abramczyk
2020-06-06T21:27:17.1746713Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-06-06T21:27:17.1747161Z ==============================================================================
2020-06-06T21:27:17.9727634Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-06-06T21:27:18.1467155Z ##[debug]Entering RunTask.
2020-06-06T21:27:18.1815014Z ##[debug]INPUT_SOURCEBRANCH: 'master'
2020-06-06T21:27:18.1915948Z ##[debug]INPUT_TARGETBRANCH: 'development/*'
2020-06-06T21:27:18.1948568Z ##[debug]INPUT_TITLE: 'AUTO MERGE BACK -- /MASTER to /DEVS'
2020-06-06T21:27:18.1984436Z ##[debug]INPUT_DESCRIPTION: 'AUTO MERGE BACK -- /MASTER to /DEVS'
2020-06-06T21:27:18.2023013Z ##[debug]INPUT_REVIEWERS (empty)
2020-06-06T21:27:18.2095466Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2020-06-06T21:27:18.2128798Z ##[debug]INPUT_ISDRAFT: 'false'
2020-06-06T21:27:18.2170837Z ##[debug] Converted to bool: False
2020-06-06T21:27:18.2206025Z ##[debug]INPUT_AUTOCOMPLETE: 'true'
2020-06-06T21:27:18.2234573Z ##[debug] Converted to bool: True
2020-06-06T21:27:18.2271581Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2020-06-06T21:27:18.2306242Z ##[debug]INPUT_DELETESOURCH: 'false'
2020-06-06T21:27:18.2332488Z ##[debug] Converted to bool: False
2020-06-06T21:27:18.2365733Z ##[debug]INPUT_COMMITMESSAGE: 'AUTO MERGE BACK -- /MASTER to /DEVS'
2020-06-06T21:27:18.2443219Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2020-06-06T21:27:18.2473911Z ##[debug] Converted to bool: False
2020-06-06T21:27:18.2515719Z ##[debug]INPUT_LINKWORKITEMS: 'false'
2020-06-06T21:27:18.2543496Z ##[debug] Converted to bool: False
2020-06-06T21:27:18.2578818Z ##[debug]INPUT_PROJECTID (empty)
2020-06-06T21:27:18.2611964Z ##[debug]INPUT_GITREPOSITORYID (empty)
2020-06-06T21:27:18.2689149Z ##[debug]INPUT_GITHUBREPOSITORY: 'embarkey-site'
2020-06-06T21:27:18.2998045Z ##[debug]Leaving RunTask.
2020-06-06T21:27:18.3153949Z ##[debug]Caught exception from task script.
2020-06-06T21:27:18.3245819Z ##[debug]Error record:
2020-06-06T21:27:18.6549073Z ##[debug]Set-Location : Cannot process argument because the value of argument "path" is null. Change the value of argument "path" to a non-null value.
2020-06-06T21:27:18.6572084Z ##[debug]At D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.133\createPullRequest.ps1:57 char:13
2020-06-06T21:27:18.6592112Z ##[debug]+             Set-Location $env:Build_SourcesDirectory
2020-06-06T21:27:18.6612493Z ##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-06-06T21:27:18.6635597Z ##[debug]    + CategoryInfo          : InvalidArgument: (:) [Set-Location], PSArgumentNullException
2020-06-06T21:27:18.6656346Z ##[debug]    + FullyQualifiedErrorId : ArgumentNull,Microsoft.PowerShell.Commands.SetLocationCommand
2020-06-06T21:27:18.7036928Z ##[debug] 
2020-06-06T21:27:18.7037507Z ##[debug]Script stack trace:
2020-06-06T21:27:18.7038418Z ##[debug]at RunTask, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.133\createPullRequest.ps1: line 57
2020-06-06T21:27:18.7039653Z ##[debug]at <ScriptBlock>, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.133\createPullRequest.ps1: line 571
2020-06-06T21:27:18.7042529Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-06-06T21:27:18.7043228Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-06-06T21:27:18.7043925Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-06-06T21:27:18.7044609Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-06-06T21:27:18.7045187Z ##[debug]Exception:
2020-06-06T21:27:18.7280355Z ##[debug]System.Management.Automation.PSArgumentNullException: Cannot process argument because the value of argument "path" is null. Change the value of argument "path" to a non-null value.
2020-06-06T21:27:18.7284042Z ##[debug]   at System.Management.Automation.SessionStateInternal.SetLocation(String path, CmdletProviderContext context)
2020-06-06T21:27:18.7285195Z ##[debug]   at Microsoft.PowerShell.Commands.SetLocationCommand.ProcessRecord()
2020-06-06T21:27:18.7286129Z ##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
2020-06-06T21:27:18.7600080Z ##[error]Cannot process argument because the value of argument "path" is null. Change the value of argument "path" to a non-null value.
2020-06-06T21:27:18.7609572Z ##[debug]Processed: ##vso[task.logissue type=error]Cannot process argument because the value of argument "path" is null. Change the value of argument "path" to a non-null value.
2020-06-06T21:27:18.7611202Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-06-06T21:27:18.8651442Z ##[section]Finishing: Create Pull Request

**Comment by blakito** [comment]
PS. Im using it on a release Pipeline, right after deploying and swapping slots

**Comment by blakito** [comment]
PS2. Only happends with multiple target branches. Took a look on the line 57 of source code and figured it out. Unfortunately i really need this feature :(

**Comment by shayki5** [comment]
Hi @blakito,
Thanks for reporting that!
You're right, the line 57 is problematic in release pipelines, I fix it :)

**Comment by shayki5** [comment]
Hi again,
I fixed it :)
Please try now.

**Comment by blakito** [comment]
Thank you very much! It's working great.

I had a permission problem because by default my "Git Repositores" permissions only had the user "Project Build Service (Project)". Giving it "Pull request" wasn't enought:
2020-06-07T21:24:06.6496375Z ##[error]{"$id":"1","innerException":null,"message":"TF401027: You need the Git 'PullRequestContribute' permission to perform this action. Details: identity 'Build\\8337f78a-bfed-4ec5-b963-f917804b7f17', scope 'repository'.","typeName":"Microsoft.TeamFoundation.Git.Server.GitNeedsPermissionException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitNeedsPermissionException","errorCode":0,"eventId":3000}
2020-06-07T21:24:06.6783509Z ##[section]Finishing: Create Pull Request

Had to give Pull permission to user "Project Collection Build Service (Project)", which only show up if you type the UUID (8837...) on "Search for user or groups". After that everything went smooth! Maybe it's worth to put on the docs :)))

**Comment by shayki5** [comment]
@blakito Great! thanks for the update!
I will update the docs with your info regarding the user Project Collection Build Service (Project).
