### ISSUE TITLE
"The remote server retruned an error: (404) Not Found."

### ISSUE THREAD

**Issue by swonge** [shayki5/azure-devops-create-pr-task#60]
I try to run the extension task, under the same organization, same setting, only with the difference git repository.
The first one is working perfectly, 

2020-08-12T22:04:18.7275359Z ##[section]Starting: Create Pull Request
2020-08-12T22:04:18.9102986Z ==============================================================================
2020-08-12T22:04:18.9109079Z Task         : Create Pull Request
2020-08-12T22:04:18.9113093Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-08-12T22:04:18.9119175Z Version      : 1.2.164
2020-08-12T22:04:18.9120125Z Author       : Shayki Abramczyk
2020-08-12T22:04:18.9126951Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-08-12T22:04:18.9127717Z ==============================================================================
2020-08-12T22:04:22.0337308Z The Source Branch is: refs/heads/SIT-RC
2020-08-12T22:04:22.0339855Z The Target Branch is: refs/heads/UAT-RC
2020-08-12T22:04:22.0340434Z The Title is: Auto merge title
2020-08-12T22:04:22.0405671Z The Description is: Descriptions goes here
2020-08-12T22:04:22.0419682Z Is Reviewers are: 
2020-08-12T22:04:22.0511904Z Is Draft Pull Request: False
2020-08-12T22:04:22.4126218Z 1 new commits! perofrm a Pull Request...
2020-08-12T22:04:22.4548910Z {
2020-08-12T22:04:22.4551312Z     "isDraft":  "False",
2020-08-12T22:04:22.4554072Z     "description":  "Descriptions goes here",
2020-08-12T22:04:22.4558427Z     "WorkItemRefs":  "",
2020-08-12T22:04:22.4561289Z     "sourceRefName":  "refs/heads/SIT-RC",
2020-08-12T22:04:22.4599950Z     "targetRefName":  "refs/heads/UAT-RC",
2020-08-12T22:04:22.4604346Z     "reviewers":  "",
2020-08-12T22:04:22.4608217Z     "title":  "Auto merge title"
2020-08-12T22:04:22.4614251Z }
2020-08-12T22:04:22.6167183Z *************************
2020-08-12T22:04:22.6180348Z ******** Success ********
2020-08-12T22:04:22.6209747Z *************************
2020-08-12T22:04:22.6222063Z Pull Request 3847 created.
2020-08-12T22:04:22.7007262Z Set Auto Complete to PR 3847.
2020-08-12T22:04:22.7742292Z ##[section]Finishing: Create Pull Request

However, I got the error message on the second one

2020-08-12T22:19:23.3550551Z ##[section]Starting: Create Pull Request - (GIT Repo: DataHub)
2020-08-12T22:19:23.4854304Z ==============================================================================
2020-08-12T22:19:23.4854970Z Task         : Create Pull Request
2020-08-12T22:19:23.4856033Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-08-12T22:19:23.4856430Z Version      : 1.2.164
2020-08-12T22:19:23.4856932Z Author       : Shayki Abramczyk
2020-08-12T22:19:23.4857568Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-08-12T22:19:23.4857973Z ==============================================================================
2020-08-12T22:19:25.0215384Z The Source Branch is: refs/heads/DEV-Master
2020-08-12T22:19:25.0218433Z The Target Branch is: refs/heads/Test-Steve
2020-08-12T22:19:25.0219746Z The Title is: Pull request automerge "DEV-Master" to "Test-Steve" - Title
2020-08-12T22:19:25.0238637Z The Description is: Pull request automerge "DEV-Master" to "Test-Steve"
2020-08-12T22:19:25.0266540Z Is Reviewers are: 
2020-08-12T22:19:25.0387806Z Is Draft Pull Request: False
2020-08-12T22:19:25.5888779Z ##[error]The remote server returned an error: (404) Not Found.
2020-08-12T22:19:25.6275625Z ##[section]Finishing: Create Pull Request - (GIT Repo: DataHub)

**Comment by shayki5** [comment]
Hi @swonge!
Can you run it again the `system.debug` = `true` and share the logs?

**Comment by shayki5** [comment]
@swonge ping...

**Comment by swonge** [comment]
Hi shayki5,

Here's the log for **successful** run
_2020-08-26T15:34:13.5388509Z ##[section]Starting: Create Pull Request - (GIT Repo: STEVE-TEST)
2020-08-26T15:34:13.6497417Z ==============================================================================
2020-08-26T15:34:13.6498082Z Task         : Create Pull Request
2020-08-26T15:34:13.6498706Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-08-26T15:34:13.6499090Z Version      : 1.2.164
2020-08-26T15:34:13.6499504Z Author       : Shayki Abramczyk
2020-08-26T15:34:13.6500119Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-08-26T15:34:13.6500510Z ==============================================================================
2020-08-26T15:34:15.3206123Z The Source Branch is: refs/heads/SIT-RC
2020-08-26T15:34:15.3208492Z The Target Branch is: refs/heads/UAT-RC
2020-08-26T15:34:15.3210622Z The Title is: Auto merge title
2020-08-26T15:34:15.3255998Z The Description is: Descriptions goes here
2020-08-26T15:34:15.3272255Z Is Reviewers are: 
2020-08-26T15:34:15.3348056Z Is Draft Pull Request: False
2020-08-26T15:34:15.9543340Z ##[warning]***************************************************************
2020-08-26T15:34:15.9569949Z ##[warning]There are no new commits in the source branch, no PR is needed!
2020-08-26T15:34:15.9572139Z ##[warning]***************************************************************
2020-08-26T15:34:16.0245507Z ##[section]Finishing: Create Pull Request - (GIT Repo: STEVE-TEST)_

Here's the log for **failed** one (under the same release)
_2020-08-26T15:34:16.0299269Z ##[section]Starting: Create Pull Request - (GIT Repo: DataHub)
2020-08-26T15:34:16.0512753Z ==============================================================================
2020-08-26T15:34:16.0513409Z Task         : Create Pull Request
2020-08-26T15:34:16.0513868Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-08-26T15:34:16.0514337Z Version      : 1.2.164
2020-08-26T15:34:16.0514578Z Author       : Shayki Abramczyk
2020-08-26T15:34:16.0515031Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-08-26T15:34:16.0515476Z ==============================================================================
2020-08-26T15:34:17.2393189Z The Source Branch is: refs/heads/DEV-Master
2020-08-26T15:34:17.2412887Z The Target Branch is: refs/heads/Test-Steve
2020-08-26T15:34:17.2428712Z The Title is: Pull request automerge "DEV-Master" to "Test-Steve" - Title
2020-08-26T15:34:17.2448722Z The Description is: Pull request automerge "DEV-Master" to "Test-Steve"
2020-08-26T15:34:17.2478528Z Is Reviewers are: 
2020-08-26T15:34:17.2607128Z Is Draft Pull Request: False
2020-08-26T15:34:17.6505331Z ##[error]The remote server returned an error: (404) Not Found.
2020-08-26T15:34:17.7078943Z ##[section]Finishing: Create Pull Request - (GIT Repo: DataHub)_

**Comment by shayki5** [comment]
Thanks @swonge.
As I said, please add variable `system.debug` with the value `true`, run it again and share the logs :)

**Comment by swonge** [comment]
Hi shayki5

Here's **successful** task:
2020-08-26T19:30:44.2910330Z ##[debug]Evaluating condition for step: 'Create Pull Request - (GIT Repo: STEVE-TEST)'
2020-08-26T19:30:44.2976262Z ##[debug]Evaluating: succeeded()
2020-08-26T19:30:44.2985178Z ##[debug]Evaluating succeeded:
2020-08-26T19:30:44.3052781Z ##[debug]=> True
2020-08-26T19:30:44.3064188Z ##[debug]Result: True
2020-08-26T19:30:44.3122209Z ##[section]Starting: Create Pull Request - (GIT Repo: STEVE-TEST)
2020-08-26T19:30:44.4213171Z ==============================================================================
2020-08-26T19:30:44.4213800Z Task         : Create Pull Request
2020-08-26T19:30:44.4214757Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-08-26T19:30:44.4215147Z Version      : 1.2.164
2020-08-26T19:30:44.4215564Z Author       : Shayki Abramczyk
2020-08-26T19:30:44.4216271Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-08-26T19:30:44.4217275Z ==============================================================================
2020-08-26T19:30:45.7230897Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-08-26T19:30:45.9839765Z ##[debug]Entering RunTask.
2020-08-26T19:30:46.0533893Z ##[debug]INPUT_SOURCEBRANCH: 'SIT-RC'
2020-08-26T19:30:46.0593952Z ##[debug]INPUT_TARGETBRANCH: 'UAT-RC'
2020-08-26T19:30:46.0639420Z ##[debug]INPUT_TITLE: 'Auto merge title'
2020-08-26T19:30:46.0686392Z ##[debug]INPUT_DESCRIPTION: 'Descriptions goes here'
2020-08-26T19:30:46.0751045Z ##[debug]INPUT_REVIEWERS (empty)
2020-08-26T19:30:46.0846096Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2020-08-26T19:30:46.0885769Z ##[debug]INPUT_ISDRAFT: 'false'
2020-08-26T19:30:46.0988474Z ##[debug] Converted to bool: False
2020-08-26T19:30:46.1057551Z ##[debug]INPUT_AUTOCOMPLETE: 'true'
2020-08-26T19:30:46.1085092Z ##[debug] Converted to bool: True
2020-08-26T19:30:46.1133541Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2020-08-26T19:30:46.1182045Z ##[debug]INPUT_DELETESOURCH: 'false'
2020-08-26T19:30:46.1243208Z ##[debug] Converted to bool: False
2020-08-26T19:30:46.1314807Z ##[debug]INPUT_COMMITMESSAGE (empty)
2020-08-26T19:30:46.1422355Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2020-08-26T19:30:46.1455164Z ##[debug] Converted to bool: False
2020-08-26T19:30:46.1500235Z ##[debug]INPUT_LINKWORKITEMS: 'false'
2020-08-26T19:30:46.1545298Z ##[debug] Converted to bool: False
2020-08-26T19:30:46.1582176Z ##[debug]INPUT_PROJECTID: '21ff51b6-ab69-4753-82ab-9a5a5640f306'
2020-08-26T19:30:46.1632640Z ##[debug]INPUT_GITREPOSITORYID: '87f372b5-b242-4dfd-80eb-f7e29e2c4e5b'
2020-08-26T19:30:46.2250478Z ##[debug]INPUT_GITHUBREPOSITORY: 'RM_DemoApp'
2020-08-26T19:30:46.2290083Z ##[debug]INPUT_PASSPULLREQUESTIDBACKTOADO: 'false'
2020-08-26T19:30:46.2349930Z ##[debug] Converted to bool: False
2020-08-26T19:30:46.2684861Z The Source Branch is: refs/heads/SIT-RC
2020-08-26T19:30:46.2702997Z The Target Branch is: refs/heads/UAT-RC
2020-08-26T19:30:46.2722629Z The Title is: Auto merge title
2020-08-26T19:30:46.2747177Z The Description is: Descriptions goes here
2020-08-26T19:30:46.2789745Z Is Reviewers are: 
2020-08-26T19:30:46.2845810Z Is Draft Pull Request: False
2020-08-26T19:30:46.4233196Z ##[debug]GET https://dev.azure.com/Vancity/21ff51b6-ab69-4753-82ab-9a5a5640f306/_apis/git/repositories/87f372b5-b242-4dfd-80eb-f7e29e2c4e5b/diffs/commits?baseVersion=SIT-RC&targetVersion=UAT-RC&api-version=4.1&$top=2 with 0-byte payload
2020-08-26T19:30:46.7617277Z ##[debug]received 261-byte response of content type application/json; charset=utf-8; api-version=4.1
2020-08-26T19:30:46.8383424Z ##[warning]***************************************************************
2020-08-26T19:30:46.8410052Z ##[debug]Processed: ##vso[task.logissue type=warning]***************************************************************
2020-08-26T19:30:46.8411831Z ##[warning]There are no new commits in the source branch, no PR is needed!
2020-08-26T19:30:46.8415826Z ##[debug]Processed: ##vso[task.logissue type=warning]There are no new commits in the source branch, no PR is needed!
2020-08-26T19:30:46.8417170Z ##[warning]***************************************************************
2020-08-26T19:30:46.8418498Z ##[debug]Processed: ##vso[task.logissue type=warning]***************************************************************
2020-08-26T19:30:46.8752312Z ##[debug]Leaving RunTask.
2020-08-26T19:30:46.9150063Z ##[section]Finishing: Create Pull Request - (GIT Repo: STEVE-TEST)


Here's **failed** task
2020-08-26T19:30:46.9198368Z ##[debug]Evaluating condition for step: 'Create Pull Request - (GIT Repo: DataHub)'
2020-08-26T19:30:46.9200530Z ##[debug]Evaluating: succeeded()
2020-08-26T19:30:46.9201166Z ##[debug]Evaluating succeeded:
2020-08-26T19:30:46.9202714Z ##[debug]=> True
2020-08-26T19:30:46.9203496Z ##[debug]Result: True
2020-08-26T19:30:46.9204273Z ##[section]Starting: Create Pull Request - (GIT Repo: DataHub)
2020-08-26T19:30:46.9378643Z ==============================================================================
2020-08-26T19:30:46.9379027Z Task         : Create Pull Request
2020-08-26T19:30:46.9379505Z Description  : Automatically create a Pull Request for Azure DevOps or GitHub repository from Build or Release pipeline, supports also multi target branch.
2020-08-26T19:30:46.9379916Z Version      : 1.2.164
2020-08-26T19:30:46.9380179Z Author       : Shayki Abramczyk
2020-08-26T19:30:46.9381123Z Help         : [More Information](https://github.com/shayki5/azure-devops-create-pr-task/blob/master/README.md)
2020-08-26T19:30:46.9381726Z ==============================================================================
2020-08-26T19:30:47.9330950Z ##[debug]VstsTaskSdk 0.10.0 commit 787a46ec0a2df5b4d12c2e801bd3f319975c054c
2020-08-26T19:30:48.1588702Z ##[debug]Entering RunTask.
2020-08-26T19:30:48.2055890Z ##[debug]INPUT_SOURCEBRANCH: 'DEV-Master'
2020-08-26T19:30:48.2123990Z ##[debug]INPUT_TARGETBRANCH: 'Test-Steve'
2020-08-26T19:30:48.2172200Z ##[debug]INPUT_TITLE: 'Pull request automerge "DEV-Master" to "Test-Steve" - Title'
2020-08-26T19:30:48.2218194Z ##[debug]INPUT_DESCRIPTION: 'Pull request automerge "DEV-Master" to "Test-Steve"'
2020-08-26T19:30:48.2272992Z ##[debug]INPUT_REVIEWERS (empty)
2020-08-26T19:30:48.2359306Z ##[debug]INPUT_REPOTYPE: 'Azure DevOps'
2020-08-26T19:30:48.2407001Z ##[debug]INPUT_ISDRAFT: 'false'
2020-08-26T19:30:48.2476310Z ##[debug] Converted to bool: False
2020-08-26T19:30:48.2576872Z ##[debug]INPUT_AUTOCOMPLETE: 'true'
2020-08-26T19:30:48.2646679Z ##[debug] Converted to bool: True
2020-08-26T19:30:48.2690095Z ##[debug]INPUT_MERGESTRATEGY: 'Merge (No fast-forward)'
2020-08-26T19:30:48.2728465Z ##[debug]INPUT_DELETESOURCH: 'false'
2020-08-26T19:30:48.2782455Z ##[debug] Converted to bool: False
2020-08-26T19:30:48.2821285Z ##[debug]INPUT_COMMITMESSAGE (empty)
2020-08-26T19:30:48.2887423Z ##[debug]INPUT_TRANSITIONWORKITEMS: 'false'
2020-08-26T19:30:48.2920004Z ##[debug] Converted to bool: False
2020-08-26T19:30:48.2991737Z ##[debug]INPUT_LINKWORKITEMS: 'false'
2020-08-26T19:30:48.3028946Z ##[debug] Converted to bool: False
2020-08-26T19:30:48.3131909Z ##[debug]INPUT_PROJECTID: '21ff51b6-ab69-4753-82ab-9a5a5640f306'
2020-08-26T19:30:48.3178223Z ##[debug]INPUT_GITREPOSITORYID: '87be368d-4653-4c1e-a6d0-a509420c2a36'
2020-08-26T19:30:48.3224822Z ##[debug]INPUT_GITHUBREPOSITORY: 'RM_DemoApp'
2020-08-26T19:30:48.3277251Z ##[debug]INPUT_PASSPULLREQUESTIDBACKTOADO: 'false'
2020-08-26T19:30:48.3308367Z ##[debug] Converted to bool: False
2020-08-26T19:30:48.3720002Z The Source Branch is: refs/heads/DEV-Master
2020-08-26T19:30:48.3757320Z The Target Branch is: refs/heads/Test-Steve
2020-08-26T19:30:48.3799331Z The Title is: Pull request automerge "DEV-Master" to "Test-Steve" - Title
2020-08-26T19:30:48.3801762Z The Description is: Pull request automerge "DEV-Master" to "Test-Steve"
2020-08-26T19:30:48.3835957Z Is Reviewers are: 
2020-08-26T19:30:48.3906377Z Is Draft Pull Request: False
2020-08-26T19:30:48.4231350Z ##[debug]GET https://dev.azure.com/Vancity/21ff51b6-ab69-4753-82ab-9a5a5640f306/_apis/git/repositories/87be368d-4653-4c1e-a6d0-a509420c2a36/diffs/commits?baseVersion=DEV-Master&targetVersion=Test-Steve&api-version=4.1&$top=2 with 0-byte payload
2020-08-26T19:30:48.7105054Z ##[debug]Leaving RunTask.
2020-08-26T19:30:48.7252605Z ##[debug]Caught exception from task script.
2020-08-26T19:30:48.7326872Z ##[debug]Error record:
2020-08-26T19:30:48.8231427Z ##[debug]Invoke-RestMethod : {"$id":"1","innerException":null,"message":"TF401175:The version descriptor  could not be resolved to a version in the repository DataHub","typeName":"Microsoft.TeamFoundation.Git.Server.GitUnresolvableToCommitException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitUnresolvableToCommitException","errorCode":0,"eventId":3000}
2020-08-26T19:30:48.8255824Z ##[debug]At D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.164\createPullRequest.ps1:363 char:17
2020-08-26T19:30:48.8281484Z ##[debug]+ ... $response = Invoke-RestMethod -Uri $url -Method Get -Headers $head -C ...
2020-08-26T19:30:48.8787120Z ##[debug]+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-08-26T19:30:48.8859124Z ##[debug]    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc    eption
2020-08-26T19:30:48.8902806Z ##[debug]    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
2020-08-26T19:30:48.9073555Z ##[debug]Script stack trace:
2020-08-26T19:30:48.9262300Z ##[debug]at CheckIfThereAreChanges, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.164\createPullRequest.ps1: line 363
2020-08-26T19:30:48.9293458Z ##[debug]at CreateAzureDevOpsPullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.164\createPullRequest.ps1: line 280
2020-08-26T19:30:48.9328547Z ##[debug]at CreatePullRequest, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.164\createPullRequest.ps1: line 121
2020-08-26T19:30:48.9336764Z ##[debug]at RunTask, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.164\createPullRequest.ps1: line 88
2020-08-26T19:30:48.9357733Z ##[debug]at <ScriptBlock>, D:\a\_tasks\CreatePullRequest_2f159376-316b-4652-a49c-392f9d534113\1.2.164\createPullRequest.ps1: line 631
2020-08-26T19:30:48.9382774Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-08-26T19:30:48.9405903Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-08-26T19:30:48.9465023Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-08-26T19:30:48.9498486Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-08-26T19:30:48.9554902Z ##[debug]Exception:
2020-08-26T19:30:49.0619058Z ##[debug]System.Net.WebException: The remote server returned an error: (404) Not Found.
2020-08-26T19:30:49.0685627Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
2020-08-26T19:30:49.0704706Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
2020-08-26T19:30:49.1329655Z ##[error]The remote server returned an error: (404) Not Found.
2020-08-26T19:30:49.1332339Z ##[debug]Processed: ##vso[task.logissue type=error]The remote server returned an error: (404) Not Found.
2020-08-26T19:30:49.1406293Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-08-26T19:30:49.2195304Z ##[section]Finishing: Create Pull Request - (GIT Repo: DataHub)

**Comment by shayki5** [comment]
Thank you @swonge!
Can you share your git repo branches?

**Comment by swonge** [comment]
Hi shayki5,
    found the issue, apparently, it's case sensitive. I used "Test-Steve" instead of "Test-STEVE". It works after I put into the right case.

Thanks

**Comment by shayki5** [comment]
Great! thank you for the update!
